// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AuthorizationScopes = "Authorization.Scopes"
)

// Defines values for ErrorCodeEnum.
const (
	BADREQUEST      ErrorCodeEnum = "BAD_REQUEST"
	CONFLICT        ErrorCodeEnum = "CONFLICT"
	FORBIDDEN       ErrorCodeEnum = "FORBIDDEN"
	INTERNALERROR   ErrorCodeEnum = "INTERNAL_ERROR"
	NOTFOUND        ErrorCodeEnum = "NOT_FOUND"
	RATELIMITED     ErrorCodeEnum = "RATE_LIMITED"
	UNAUTHORIZED    ErrorCodeEnum = "UNAUTHORIZED"
	VALIDATIONERROR ErrorCodeEnum = "VALIDATION_ERROR"
)

// Defines values for EventActivityKindEnum.
const (
	EventActivityKindEnumFreeRange EventActivityKindEnum = "free_range"
	EventActivityKindEnumOther     EventActivityKindEnum = "other"
	EventActivityKindEnumPlay      EventActivityKindEnum = "play"
	EventActivityKindEnumSwim      EventActivityKindEnum = "swim"
	EventActivityKindEnumTraining  EventActivityKindEnum = "training"
	EventActivityKindEnumWalk      EventActivityKindEnum = "walk"
)

// Defines values for EventExcretionStatusEnum.
const (
	Abnormal EventExcretionStatusEnum = "abnormal"
	Normal   EventExcretionStatusEnum = "normal"
)

// Defines values for EventFeedingFoodEnum.
const (
	EventFeedingFoodEnumDry        EventFeedingFoodEnum = "dry"
	EventFeedingFoodEnumFrozenPrey EventFeedingFoodEnum = "frozen_prey"
	EventFeedingFoodEnumGrain      EventFeedingFoodEnum = "grain"
	EventFeedingFoodEnumGreens     EventFeedingFoodEnum = "greens"
	EventFeedingFoodEnumHay        EventFeedingFoodEnum = "hay"
	EventFeedingFoodEnumHomemade   EventFeedingFoodEnum = "homemade"
	EventFeedingFoodEnumInsects    EventFeedingFoodEnum = "insects"
	EventFeedingFoodEnumLivePrey   EventFeedingFoodEnum = "live_prey"
	EventFeedingFoodEnumOther      EventFeedingFoodEnum = "other"
	EventFeedingFoodEnumRaw        EventFeedingFoodEnum = "raw"
	EventFeedingFoodEnumTreat      EventFeedingFoodEnum = "treat"
	EventFeedingFoodEnumWet        EventFeedingFoodEnum = "wet"
)

// Defines values for EventFeedingUnitEnum.
const (
	EventFeedingUnitEnumG       EventFeedingUnitEnum = "g"
	EventFeedingUnitEnumMl      EventFeedingUnitEnum = "ml"
	EventFeedingUnitEnumPiece   EventFeedingUnitEnum = "piece"
	EventFeedingUnitEnumPortion EventFeedingUnitEnum = "portion"
)

// Defines values for EventHygieneProcedureEnum.
const (
	EventHygieneProcedureEnumAntiparasitic EventHygieneProcedureEnum = "antiparasitic"
	EventHygieneProcedureEnumBath          EventHygieneProcedureEnum = "bath"
	EventHygieneProcedureEnumBeak          EventHygieneProcedureEnum = "beak"
	EventHygieneProcedureEnumBrushing      EventHygieneProcedureEnum = "brushing"
	EventHygieneProcedureEnumEars          EventHygieneProcedureEnum = "ears"
	EventHygieneProcedureEnumEnclosure     EventHygieneProcedureEnum = "enclosure"
	EventHygieneProcedureEnumNails         EventHygieneProcedureEnum = "nails"
	EventHygieneProcedureEnumOther         EventHygieneProcedureEnum = "other"
	EventHygieneProcedureEnumShedding      EventHygieneProcedureEnum = "shedding"
	EventHygieneProcedureEnumTeeth         EventHygieneProcedureEnum = "teeth"
	EventHygieneProcedureEnumWaterChange   EventHygieneProcedureEnum = "water_change"
)

// Defines values for EventMedicationDoseUnitEnum.
const (
	EventMedicationDoseUnitEnumCapsule EventMedicationDoseUnitEnum = "capsule"
	EventMedicationDoseUnitEnumDrop    EventMedicationDoseUnitEnum = "drop"
	EventMedicationDoseUnitEnumG       EventMedicationDoseUnitEnum = "g"
	EventMedicationDoseUnitEnumMcg     EventMedicationDoseUnitEnum = "mcg"
	EventMedicationDoseUnitEnumMg      EventMedicationDoseUnitEnum = "mg"
	EventMedicationDoseUnitEnumMl      EventMedicationDoseUnitEnum = "ml"
	EventMedicationDoseUnitEnumTablet  EventMedicationDoseUnitEnum = "tablet"
)

// Defines values for EventMoodStateEnum.
const (
	Aggressive EventMoodStateEnum = "aggressive"
	Anxious    EventMoodStateEnum = "anxious"
	Calm       EventMoodStateEnum = "calm"
	Hiding     EventMoodStateEnum = "hiding"
	Lethargic  EventMoodStateEnum = "lethargic"
	Playful    EventMoodStateEnum = "playful"
)

// Defines values for EventStatsAggregationEnum.
const (
	Avg   EventStatsAggregationEnum = "avg"
	Count EventStatsAggregationEnum = "count"
	Last  EventStatsAggregationEnum = "last"
	Sum   EventStatsAggregationEnum = "sum"
)

// Defines values for EventStatsBucketEnum.
const (
	Day   EventStatsBucketEnum = "day"
	Month EventStatsBucketEnum = "month"
	Week  EventStatsBucketEnum = "week"
)

// Defines values for EventStatsValueKindEnum.
const (
	Category EventStatsValueKindEnum = "category"
	Measure  EventStatsValueKindEnum = "measure"
	Quantity EventStatsValueKindEnum = "quantity"
)

// Defines values for EventTemperatureKindEnum.
const (
	Body        EventTemperatureKindEnum = "body"
	Environment EventTemperatureKindEnum = "environment"
)

// Defines values for GetEventEnum.
const (
	GetEventEnumActivity    GetEventEnum = "activity"
	GetEventEnumDefecation  GetEventEnum = "defecation"
	GetEventEnumDiarrhea    GetEventEnum = "diarrhea"
	GetEventEnumFeeding     GetEventEnum = "feeding"
	GetEventEnumHygiene     GetEventEnum = "hygiene"
	GetEventEnumMedication  GetEventEnum = "medication"
	GetEventEnumMood        GetEventEnum = "mood"
	GetEventEnumOther       GetEventEnum = "other"
	GetEventEnumSleep       GetEventEnum = "sleep"
	GetEventEnumTemperature GetEventEnum = "temperature"
	GetEventEnumUrine       GetEventEnum = "urine"
	GetEventEnumVomit       GetEventEnum = "vomit"
	GetEventEnumWater       GetEventEnum = "water"
	GetEventEnumWeight      GetEventEnum = "weight"
)

// Defines values for GetGenderEnum.
const (
	Female GetGenderEnum = "female"
	Male   GetGenderEnum = "male"
	Other  GetGenderEnum = "other"
)

// Defines values for GetHabilitationEnum.
const (
	Both    GetHabilitationEnum = "both"
	Indoor  GetHabilitationEnum = "indoor"
	Outside GetHabilitationEnum = "outside"
)

// Defines values for PetIconEnum.
const (
	ANTFARM      PetIconEnum = "ANT_FARM"
	AXOLOTL      PetIconEnum = "AXOLOTL"
	BEARDEDAGAMA PetIconEnum = "BEARDED_AGAMA"
	CANARY       PetIconEnum = "CANARY"
	CAT          PetIconEnum = "CAT"
	CHICKEN      PetIconEnum = "CHICKEN"
	CHINCHILLA   PetIconEnum = "CHINCHILLA"
	DOG          PetIconEnum = "DOG"
	DUCK         PetIconEnum = "DUCK"
	FERRET       PetIconEnum = "FERRET"
	FISH         PetIconEnum = "FISH"
	FROG         PetIconEnum = "FROG"
	GECKO        PetIconEnum = "GECKO"
	GUINEAPIG    PetIconEnum = "GUINEA_PIG"
	HAMSTER      PetIconEnum = "HAMSTER"
	HEDGEHOG     PetIconEnum = "HEDGEHOG"
	HERMITCRAB   PetIconEnum = "HERMIT_CRAB"
	IGUANA       PetIconEnum = "IGUANA"
	MINIGOAT     PetIconEnum = "MINI_GOAT"
	MINIPIG      PetIconEnum = "MINI_PIG"
	MOUSE        PetIconEnum = "MOUSE"
	OTHER        PetIconEnum = "OTHER"
	PARROT       PetIconEnum = "PARROT"
	PIGEON       PetIconEnum = "PIGEON"
	PYTHON       PetIconEnum = "PYTHON"
	RABBIT       PetIconEnum = "RABBIT"
	RAT          PetIconEnum = "RAT"
	SNAIL        PetIconEnum = "SNAIL"
	SNAKE        PetIconEnum = "SNAKE"
	TARANTULA    PetIconEnum = "TARANTULA"
	TURTLE       PetIconEnum = "TURTLE"
)

// Defines values for LanguageCode.
const (
	En LanguageCode = "en"
	Ru LanguageCode = "ru"
)

// ErrorCodeEnum Код ошибки для маппинга на фронте
type ErrorCodeEnum string

// EventActivityKindEnum Вид активности (value.kind при type=activity). free_range — время вне клетки, вольера или террариума.
type EventActivityKindEnum string

// EventExcretionStatusEnum Статус выделений (value.status при type=urine|defecation|vomit|diarrhea).
type EventExcretionStatusEnum string

// EventFeedingFoodEnum Вид корма (value.food при type=feeding).
type EventFeedingFoodEnum string

// EventFeedingUnitEnum Единица измерения кормления (value.unit при type=feeding). piece — счётные корма (кормовые грызуны, насекомые, мальки).
type EventFeedingUnitEnum string

// EventHygieneProcedureEnum Процедура гигиены (value.procedure при type=hygiene).
type EventHygieneProcedureEnum string

// EventMedicationDoseUnitEnum Единица дозы лекарства (value.dose_unit при type=medication).
type EventMedicationDoseUnitEnum string

// EventMoodStateEnum Состояние питомца (value.state при type=mood).
type EventMoodStateEnum string

// EventStatsAggregationEnum Способ свёртки значений метрики внутри интервала, применённый к этой серии.
type EventStatsAggregationEnum string

// EventStatsBucket defines model for EventStatsBucket.
type EventStatsBucket struct {
	// BucketStart Дата начала интервала (UTC).
	BucketStart openapi_types.Date `json:"bucket_start"`

	// Count Количество событий, попавших в интервал.
	Count int `json:"count"`

	// Value Агрегированное значение интервала; null — событий в интервале не было.
	Value *float32 `json:"value"`
}

// EventStatsBucketEnum Интервал агрегации графика. week — календарная неделя по UTC с понедельника, month — календарный месяц по UTC.
type EventStatsBucketEnum string

// EventStatsSeries defines model for EventStatsSeries.
type EventStatsSeries struct {
	// Aggregation Способ свёртки значений метрики внутри интервала, применённый к этой серии.
	Aggregation EventStatsAggregationEnum `json:"aggregation"`

	// Buckets Точки серии по интервалам, по возрастанию bucket_start. Интервалы без событий присутствуют с value=null и count=0.
	Buckets []EventStatsBucket `json:"buckets"`

	// Category Значение, разделяющее серии одного типа: при value_kind=category — конкретное значение категории (procedure, state, status); при type=temperature — вид замера (EventTemperatureKindEnum). Отсутствует, если тип даёт одну серию.
	Category *string `json:"category,omitempty"`

	// Metric Ключ метрики из реестра метрик (например amount_avg, amount_last, amount_sum, duration_min_sum, distance_m_sum, count).
	Metric string       `json:"metric"`
	Type   GetEventEnum `json:"type"`

	// Unit Единица измерения значений серии; отсутствует, если у метрики нет единицы (категориальные серии, количество приёмов).
	Unit *string `json:"unit,omitempty"`

	// ValueKind Характер значения серии; определяет форму графика на клиенте. Тип с value_kind=label (other) не агрегируется и в ответе не встречается.
	ValueKind EventStatsValueKindEnum `json:"value_kind"`
}

// EventStatsValueKindEnum Характер значения серии; определяет форму графика на клиенте. Тип с value_kind=label (other) не агрегируется и в ответе не встречается.
type EventStatsValueKindEnum string

// EventTemperatureKindEnum Вид замера температуры (value.kind при type=temperature): body — температура тела, environment — температура среды обитания (террариум, точка прогрева, вода аквариума).
type EventTemperatureKindEnum string

// EventValue Типизированное значение события. Состав полей определяется полем type события (размеченное объединение, дискриминатор — type; см. требование «Модель значения события и реестр метрик»). На уровне схемы перечислены все возможные поля; обязательность, диапазоны и допустимость поля для конкретного type проверяются сервером по единому реестру метрик. Поле, не описанное формой value для данного type, даёт 400, а не игнорируется молча.
//
// Состав по типам:
// * weight — amount (кг, 0.001–400)
// * temperature — amount (°C, 0–50), kind (EventTemperatureKindEnum)
// * feeding — amount (0.01–5000), unit, food
// * water — amount (мл, 0.1–5000)
// * activity — duration_min (1–1440), kind (EventActivityKindEnum), distance_m (0–100000, опционально)
// * sleep — duration_min (1–1440)
// * medication — name (1–100), dose_amount (0.001–10000) и dose_unit — только вместе, опционально
// * hygiene — procedure
// * mood — state
// * urine, defecation, vomit, diarrhea — status
// * other — label (1–50)
type EventValue struct {
	// Amount Числовая величина: weight (кг), temperature (°C), feeding (в единице unit), water (мл).
	Amount *float32 `json:"amount,omitempty"`

	// DistanceM Дистанция в метрах (type=activity, опционально).
	DistanceM *float32 `json:"distance_m,omitempty"`

	// DoseAmount Доза препарата в единице dose_unit (type=medication, только вместе с dose_unit).
	DoseAmount *float32 `json:"dose_amount,omitempty"`

	// DoseUnit Единица дозы лекарства (value.dose_unit при type=medication).
	DoseUnit *EventMedicationDoseUnitEnum `json:"dose_unit,omitempty"`

	// DurationMin Длительность в минутах: activity, sleep.
	DurationMin *float32 `json:"duration_min,omitempty"`

	// Food Вид корма (value.food при type=feeding).
	Food *EventFeedingFoodEnum `json:"food,omitempty"`

	// Kind Вид наблюдения: при type=temperature — значение EventTemperatureKindEnum, при type=activity — значение EventActivityKindEnum.
	Kind *string `json:"kind,omitempty"`

	// Label Краткое обозначение события (type=other); подробности — в notes.
	Label *string `json:"label,omitempty"`

	// Name Название препарата (type=medication).
	Name *string `json:"name,omitempty"`

	// Procedure Процедура гигиены (value.procedure при type=hygiene).
	Procedure *EventHygieneProcedureEnum `json:"procedure,omitempty"`

	// State Состояние питомца (value.state при type=mood).
	State *EventMoodStateEnum `json:"state,omitempty"`

	// Status Статус выделений (value.status при type=urine|defecation|vomit|diarrhea).
	Status *EventExcretionStatusEnum `json:"status,omitempty"`

	// Unit Единица измерения кормления (value.unit при type=feeding). piece — счётные корма (кормовые грызуны, насекомые, мальки).
	Unit *EventFeedingUnitEnum `json:"unit,omitempty"`
}

// GetActivitiesResponse defines model for GetActivitiesResponse.
type GetActivitiesResponse struct {
	Items   []ItemsArrayActivitiesModel `json:"items"`
	PetName string                      `json:"pet_name"`
}

// GetErrorResponse defines model for GetErrorResponse.
type GetErrorResponse struct {
	// Code Код ошибки для маппинга на фронте
	Code ErrorCodeEnum `json:"code"`

	// Message Техническое описание ошибки для отладки
	Message string `json:"message"`

	// Payload Произвольные дополнительные данные об ошибке
	Payload *interface{} `json:"payload,omitempty"`
}

// GetEventEnum defines model for GetEventEnum.
type GetEventEnum string

// GetEventIdResponseRequest defines model for GetEventIdResponseRequest.
type GetEventIdResponseRequest struct {
	Date    time.Time          `json:"date"`
	Id      openapi_types.UUID `json:"id"`
	Notes   *string            `json:"notes,omitempty"`
	PetId   openapi_types.UUID `json:"pet_id"`
	PetName string             `json:"pet_name"`
	Type    GetEventEnum       `json:"type"`

	// Value Типизированное значение события. Состав полей определяется полем type события (размеченное объединение, дискриминатор — type; см. требование «Модель значения события и реестр метрик»). На уровне схемы перечислены все возможные поля; обязательность, диапазоны и допустимость поля для конкретного type проверяются сервером по единому реестру метрик. Поле, не описанное формой value для данного type, даёт 400, а не игнорируется молча.
	//
	// Состав по типам:
	// * weight — amount (кг, 0.001–400)
	// * temperature — amount (°C, 0–50), kind (EventTemperatureKindEnum)
	// * feeding — amount (0.01–5000), unit, food
	// * water — amount (мл, 0.1–5000)
	// * activity — duration_min (1–1440), kind (EventActivityKindEnum), distance_m (0–100000, опционально)
	// * sleep — duration_min (1–1440)
	// * medication — name (1–100), dose_amount (0.001–10000) и dose_unit — только вместе, опционально
	// * hygiene — procedure
	// * mood — state
	// * urine, defecation, vomit, diarrhea — status
	// * other — label (1–50)
	Value EventValue `json:"value"`
}

// GetEventRequest defines model for GetEventRequest.
type GetEventRequest struct {
	Date  time.Time          `json:"date"`
	Notes *string            `json:"notes,omitempty"`
	PetId openapi_types.UUID `json:"pet_id"`
	Type  GetEventEnum       `json:"type"`

	// Value Типизированное значение события. Состав полей определяется полем type события (размеченное объединение, дискриминатор — type; см. требование «Модель значения события и реестр метрик»). На уровне схемы перечислены все возможные поля; обязательность, диапазоны и допустимость поля для конкретного type проверяются сервером по единому реестру метрик. Поле, не описанное формой value для данного type, даёт 400, а не игнорируется молча.
	//
	// Состав по типам:
	// * weight — amount (кг, 0.001–400)
	// * temperature — amount (°C, 0–50), kind (EventTemperatureKindEnum)
	// * feeding — amount (0.01–5000), unit, food
	// * water — amount (мл, 0.1–5000)
	// * activity — duration_min (1–1440), kind (EventActivityKindEnum), distance_m (0–100000, опционально)
	// * sleep — duration_min (1–1440)
	// * medication — name (1–100), dose_amount (0.001–10000) и dose_unit — только вместе, опционально
	// * hygiene — procedure
	// * mood — state
	// * urine, defecation, vomit, diarrhea — status
	// * other — label (1–50)
	Value EventValue `json:"value"`
}

// GetEventResponse defines model for GetEventResponse.
type GetEventResponse struct {
	Date  time.Time          `json:"date"`
	Id    openapi_types.UUID `json:"id"`
	Notes *string            `json:"notes,omitempty"`
	Type  GetEventEnum       `json:"type"`

	// Value Типизированное значение события. Состав полей определяется полем type события (размеченное объединение, дискриминатор — type; см. требование «Модель значения события и реестр метрик»). На уровне схемы перечислены все возможные поля; обязательность, диапазоны и допустимость поля для конкретного type проверяются сервером по единому реестру метрик. Поле, не описанное формой value для данного type, даёт 400, а не игнорируется молча.
	//
	// Состав по типам:
	// * weight — amount (кг, 0.001–400)
	// * temperature — amount (°C, 0–50), kind (EventTemperatureKindEnum)
	// * feeding — amount (0.01–5000), unit, food
	// * water — amount (мл, 0.1–5000)
	// * activity — duration_min (1–1440), kind (EventActivityKindEnum), distance_m (0–100000, опционально)
	// * sleep — duration_min (1–1440)
	// * medication — name (1–100), dose_amount (0.001–10000) и dose_unit — только вместе, опционально
	// * hygiene — procedure
	// * mood — state
	// * urine, defecation, vomit, diarrhea — status
	// * other — label (1–50)
	Value EventValue `json:"value"`
}

// GetEventStatsResponse defines model for GetEventStatsResponse.
type GetEventStatsResponse struct {
	PetName string             `json:"pet_name"`
	Series  []EventStatsSeries `json:"series"`
}

// GetGenderEnum defines model for GetGenderEnum.
type GetGenderEnum string

// GetGuestRequest defines model for GetGuestRequest.
type GetGuestRequest struct {
	DeviceId string `json:"device_id"`
}

// GetHabilitationEnum defines model for GetHabilitationEnum.
type GetHabilitationEnum string

// GetLoginRequest defines model for GetLoginRequest.
type GetLoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// GetLoginResponse defines model for GetLoginResponse.
type GetLoginResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// GetMasterProfileResponse defines model for GetMasterProfileResponse.
type GetMasterProfileResponse struct {
	Email     *string `json:"email"`
	FirstName string  `json:"first_name"`

	// Id Идентификатор пользователя (users.id), а не первичный ключ строки profile
	Id         openapi_types.UUID `json:"id"`
	LastName   *string            `json:"last_name"`
	Login      string             `json:"login"`
	MiddleName *string            `json:"middle_name"`
	Phone      *string            `json:"phone"`
}

// GetPetProfileRequest defines model for GetPetProfileRequest.
type GetPetProfileRequest struct {
	BirthDate  *openapi_types.Date  `json:"birth_date,omitempty"`
	Breed      *string              `json:"breed,omitempty"`
	Color      *string              `json:"color,omitempty"`
	Gender     *GetGenderEnum       `json:"gender,omitempty"`
	Habitation *GetHabilitationEnum `json:"habitation,omitempty"`
	Name       string               `json:"name"`
	Notes      *string              `json:"notes,omitempty"`
	Species    string               `json:"species"`
	Sterilized *bool                `json:"sterilized,omitempty"`
}

// GetPetProfileResponse defines model for GetPetProfileResponse.
type GetPetProfileResponse struct {
	BirthDate  *openapi_types.Date  `json:"birth_date,omitempty"`
	Breed      *string              `json:"breed,omitempty"`
	Color      *string              `json:"color"`
	Gender     *GetGenderEnum       `json:"gender,omitempty"`
	Habitation *GetHabilitationEnum `json:"habitation,omitempty"`
	Icon       PetIconEnum          `json:"icon"`
	Id         openapi_types.UUID   `json:"id"`
	IsDeleted  *bool                `json:"is_deleted,omitempty"`
	Name       string               `json:"name"`
	Notes      *string              `json:"notes"`

	// PhotoFileId id файла фотографии для DELETE /files/{file_id}; null если фотографии нет
	PhotoFileId *openapi_types.UUID `json:"photo_file_id"`

	// PhotoUrl Presigned GET URL на текущую фотографию питомца, временная ссылка с TTL; null если фотографии нет
	PhotoUrl   *string `json:"photo_url"`
	Species    string  `json:"species"`
	Sterilized *bool   `json:"sterilized,omitempty"`
}

// GetProfileRequest defines model for GetProfileRequest.
type GetProfileRequest struct {
	Email      *openapi_types.Email `json:"email,omitempty"`
	FirstName  string               `json:"first_name"`
	LastName   *string              `json:"last_name,omitempty"`
	MiddleName *string              `json:"middle_name,omitempty"`
	Phone      *string              `json:"phone,omitempty"`
}

// GetProfileUpdateRequest Частичное обновление профиля через PUT /profile: все поля необязательны, но должно быть передано хотя бы одно. Если первое имя (first_name) передано явно, оно не может быть пустой строкой.
type GetProfileUpdateRequest struct {
	Email      *openapi_types.Email `json:"email,omitempty"`
	FirstName  *string              `json:"first_name,omitempty"`
	LastName   *string              `json:"last_name,omitempty"`
	MiddleName *string              `json:"middle_name,omitempty"`
	Phone      *string              `json:"phone,omitempty"`
}

// GetRefreshRequest defines model for GetRefreshRequest.
type GetRefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// GetShortInfoAllPetResponse defines model for GetShortInfoAllPetResponse.
type GetShortInfoAllPetResponse struct {
	Items []GetShortInfoPetResponse `json:"items"`
}

// GetShortInfoPetResponse defines model for GetShortInfoPetResponse.
type GetShortInfoPetResponse struct {
	Breed string             `json:"breed"`
	Icon  PetIconEnum        `json:"icon"`
	Id    openapi_types.UUID `json:"id"`
	Name  string             `json:"name"`

	// PhotoUrl Presigned GET URL на текущую фотографию питомца, временная ссылка с TTL; null если фотографии нет
	PhotoUrl *string `json:"photo_url"`
	Species  string  `json:"species"`
}

// ImportLocalDataEvent defines model for ImportLocalDataEvent.
type ImportLocalDataEvent struct {
	Date  time.Time `json:"date"`
	Notes *string   `json:"notes,omitempty"`

	// PetLocalId Должен совпадать с одним из pets[].local_id этого же запроса.
	PetLocalId string       `json:"pet_local_id"`
	Type       GetEventEnum `json:"type"`

	// Value Типизированное значение события. Состав полей определяется полем type события (размеченное объединение, дискриминатор — type; см. требование «Модель значения события и реестр метрик»). На уровне схемы перечислены все возможные поля; обязательность, диапазоны и допустимость поля для конкретного type проверяются сервером по единому реестру метрик. Поле, не описанное формой value для данного type, даёт 400, а не игнорируется молча.
	//
	// Состав по типам:
	// * weight — amount (кг, 0.001–400)
	// * temperature — amount (°C, 0–50), kind (EventTemperatureKindEnum)
	// * feeding — amount (0.01–5000), unit, food
	// * water — amount (мл, 0.1–5000)
	// * activity — duration_min (1–1440), kind (EventActivityKindEnum), distance_m (0–100000, опционально)
	// * sleep — duration_min (1–1440)
	// * medication — name (1–100), dose_amount (0.001–10000) и dose_unit — только вместе, опционально
	// * hygiene — procedure
	// * mood — state
	// * urine, defecation, vomit, diarrhea — status
	// * other — label (1–50)
	Value EventValue `json:"value"`
}

// ImportLocalDataPet defines model for ImportLocalDataPet.
type ImportLocalDataPet struct {
	BirthDate  *openapi_types.Date  `json:"birth_date,omitempty"`
	Breed      *string              `json:"breed,omitempty"`
	Color      *string              `json:"color,omitempty"`
	Gender     *GetGenderEnum       `json:"gender,omitempty"`
	Habitation *GetHabilitationEnum `json:"habitation,omitempty"`

	// LocalId Клиентский UUID питомца в локальном хранилище устройства; используется только как временный ключ ссылки внутри этого запроса (для сопоставления с events[].pet_local_id), не сохраняется на сервере.
	LocalId    string  `json:"local_id"`
	Name       string  `json:"name"`
	Notes      *string `json:"notes,omitempty"`
	Species    string  `json:"species"`
	Sterilized *bool   `json:"sterilized,omitempty"`
}

// ImportLocalDataRequest defines model for ImportLocalDataRequest.
type ImportLocalDataRequest struct {
	Events  []ImportLocalDataEvent `json:"events"`
	Pets    []ImportLocalDataPet   `json:"pets"`
	Profile *GetProfileRequest     `json:"profile,omitempty"`
}

// ImportLocalDataResponse defines model for ImportLocalDataResponse.
type ImportLocalDataResponse struct {
	EventsImported int `json:"events_imported"`

	// Pets Сопоставление local_id -> серверный id для каждого перенесённого питомца, в порядке pets запроса. Используется клиентом для фонового переноса фотографий (см. «Фотография питомца — Frontend (dataSource=local)»).
	Pets            []ImportedPet `json:"pets"`
	PetsImported    int           `json:"pets_imported"`
	ProfileImported bool          `json:"profile_imported"`
}

// ImportedPet defines model for ImportedPet.
type ImportedPet struct {
	Id      openapi_types.UUID `json:"id"`
	LocalId string             `json:"local_id"`
}

// ItemsArrayActivitiesModel defines model for ItemsArrayActivitiesModel.
type ItemsArrayActivitiesModel struct {
	Date   openapi_types.Date `json:"date"`
	Events []GetEventResponse `json:"events"`
}

// PetIconEnum defines model for PetIconEnum.
type PetIconEnum string

// PostFilesUploadUrlRequest defines model for PostFilesUploadUrlRequest.
type PostFilesUploadUrlRequest struct {
	// ContentType MIME-тип файла, должен входить в список допустимых для данного owner_type
	ContentType string             `json:"content_type"`
	OwnerId     openapi_types.UUID `json:"owner_id"`

	// OwnerType Тип владельца файла из реестра типов владельцев, например pet_photo
	OwnerType string `json:"owner_type"`
}

// PostFilesUploadUrlResponse defines model for PostFilesUploadUrlResponse.
type PostFilesUploadUrlResponse struct {
	ContentType string `json:"content_type"`

	// ExpiresIn Время жизни presigned URL в секундах
	ExpiresIn int                `json:"expires_in"`
	FileId    openapi_types.UUID `json:"file_id"`

	// UploadUrl Presigned PUT URL для прямой загрузки в S3-совместимое хранилище
	UploadUrl string `json:"upload_url"`
}

// UpdateEventRequest defines model for UpdateEventRequest.
type UpdateEventRequest struct {
	Date  *time.Time         `json:"date,omitempty"`
	Notes *string            `json:"notes,omitempty"`
	PetId openapi_types.UUID `json:"pet_id"`
	Type  *GetEventEnum      `json:"type,omitempty"`

	// Value Типизированное значение события. Состав полей определяется полем type события (размеченное объединение, дискриминатор — type; см. требование «Модель значения события и реестр метрик»). На уровне схемы перечислены все возможные поля; обязательность, диапазоны и допустимость поля для конкретного type проверяются сервером по единому реестру метрик. Поле, не описанное формой value для данного type, даёт 400, а не игнорируется молча.
	//
	// Состав по типам:
	// * weight — amount (кг, 0.001–400)
	// * temperature — amount (°C, 0–50), kind (EventTemperatureKindEnum)
	// * feeding — amount (0.01–5000), unit, food
	// * water — amount (мл, 0.1–5000)
	// * activity — duration_min (1–1440), kind (EventActivityKindEnum), distance_m (0–100000, опционально)
	// * sleep — duration_min (1–1440)
	// * medication — name (1–100), dose_amount (0.001–10000) и dose_unit — только вместе, опционально
	// * hygiene — procedure
	// * mood — state
	// * urine, defecation, vomit, diarrhea — status
	// * other — label (1–50)
	Value *EventValue `json:"value,omitempty"`
}

// UpdatePetProfileRequest defines model for UpdatePetProfileRequest.
type UpdatePetProfileRequest struct {
	BirthDate  *openapi_types.Date  `json:"birth_date,omitempty"`
	Breed      *string              `json:"breed,omitempty"`
	Color      *string              `json:"color,omitempty"`
	Gender     *GetGenderEnum       `json:"gender,omitempty"`
	Habitation *GetHabilitationEnum `json:"habitation,omitempty"`
	Name       *string              `json:"name,omitempty"`
	Notes      *string              `json:"notes,omitempty"`
	Species    *string              `json:"species,omitempty"`
	Sterilized *bool                `json:"sterilized,omitempty"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// IdempotencyKeyRequired defines model for IdempotencyKeyRequired.
type IdempotencyKeyRequired = openapi_types.UUID

// LanguageCode defines model for LanguageCode.
type LanguageCode string

// GetActivitiesParams defines parameters for GetActivities.
type GetActivitiesParams struct {
	PetId openapi_types.UUID `form:"pet_id" json:"pet_id"`
	From  openapi_types.Date `form:"from" json:"from"`
	To    openapi_types.Date `form:"to" json:"to"`
}

// PostEventParams defines parameters for PostEvent.
type PostEventParams struct {
	// IdempotencyKey UUID v4, генерируется клиентом один раз при открытии формы добавления события; повторная отправка с тем же ключом возвращает ранее созданное событие вместо дубликата.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetEventsStatsParams defines parameters for GetEventsStats.
type GetEventsStatsParams struct {
	PetId openapi_types.UUID `form:"pet_id" json:"pet_id"`

	// Types Список значений type через запятую. По умолчанию — все типы, у которых value_kind ≠ label.
	Types  *string              `form:"types,omitempty" json:"types,omitempty"`
	From   openapi_types.Date   `form:"from" json:"from"`
	To     openapi_types.Date   `form:"to" json:"to"`
	Bucket EventStatsBucketEnum `form:"bucket" json:"bucket"`
}

// PostImportLocalDataParams defines parameters for PostImportLocalData.
type PostImportLocalDataParams struct {
	// IdempotencyKey UUID v4, генерируется клиентом один раз на попытку переноса локальных данных; повторная отправка с тем же ключом в течение окна дедупликации возвращает ранее сохранённый результат переноса вместо повторного создания сущностей.
	IdempotencyKey IdempotencyKeyRequired `json:"Idempotency-Key"`
}

// PostPetParams defines parameters for PostPet.
type PostPetParams struct {
	// IdempotencyKey UUID v4, генерируется клиентом один раз при открытии формы добавления события; повторная отправка с тем же ключом возвращает ранее созданное событие вместо дубликата.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetPetEventsParams defines parameters for GetPetEvents.
type GetPetEventsParams struct {
	// Limit Максимум записей в ответе. По умолчанию 50, значения больше 200 молча ограничиваются до 200.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для пагинации. По умолчанию 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostGuestJSONRequestBody defines body for PostGuest for application/json ContentType.
type PostGuestJSONRequestBody = GetGuestRequest

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = GetLoginRequest

// PostLogoutJSONRequestBody defines body for PostLogout for application/json ContentType.
type PostLogoutJSONRequestBody = GetRefreshRequest

// PostRefreshJSONRequestBody defines body for PostRefresh for application/json ContentType.
type PostRefreshJSONRequestBody = GetRefreshRequest

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody = GetLoginRequest

// PostEventJSONRequestBody defines body for PostEvent for application/json ContentType.
type PostEventJSONRequestBody = GetEventRequest

// PatchEventJSONRequestBody defines body for PatchEvent for application/json ContentType.
type PatchEventJSONRequestBody = UpdateEventRequest

// PostFilesUploadUrlJSONRequestBody defines body for PostFilesUploadUrl for application/json ContentType.
type PostFilesUploadUrlJSONRequestBody = PostFilesUploadUrlRequest

// PostImportLocalDataJSONRequestBody defines body for PostImportLocalData for application/json ContentType.
type PostImportLocalDataJSONRequestBody = ImportLocalDataRequest

// PostPetJSONRequestBody defines body for PostPet for application/json ContentType.
type PostPetJSONRequestBody = GetPetProfileRequest

// PutPetJSONRequestBody defines body for PutPet for application/json ContentType.
type PutPetJSONRequestBody = UpdatePetProfileRequest

// PostProfileJSONRequestBody defines body for PostProfile for application/json ContentType.
type PostProfileJSONRequestBody = GetProfileRequest

// PutProfileJSONRequestBody defines body for PutProfile for application/json ContentType.
type PutProfileJSONRequestBody = GetProfileUpdateRequest
