// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AuthorizationScopes = "Authorization.Scopes"
)

// Defines values for ErrorCodeEnum.
const (
	BADREQUEST      ErrorCodeEnum = "BAD_REQUEST"
	CONFLICT        ErrorCodeEnum = "CONFLICT"
	FORBIDDEN       ErrorCodeEnum = "FORBIDDEN"
	INTERNALERROR   ErrorCodeEnum = "INTERNAL_ERROR"
	NOTFOUND        ErrorCodeEnum = "NOT_FOUND"
	RATELIMITED     ErrorCodeEnum = "RATE_LIMITED"
	UNAUTHORIZED    ErrorCodeEnum = "UNAUTHORIZED"
	VALIDATIONERROR ErrorCodeEnum = "VALIDATION_ERROR"
)

// Defines values for GetEventEnum.
const (
	GetEventEnumDefecation GetEventEnum = "defecation"
	GetEventEnumDiarrhea   GetEventEnum = "diarrhea"
	GetEventEnumOther      GetEventEnum = "other"
	GetEventEnumUrine      GetEventEnum = "urine"
	GetEventEnumVomit      GetEventEnum = "vomit"
	GetEventEnumWeight     GetEventEnum = "weight"
)

// Defines values for GetGenderEnum.
const (
	GetGenderEnumFemale GetGenderEnum = "female"
	GetGenderEnumMale   GetGenderEnum = "male"
	GetGenderEnumOther  GetGenderEnum = "other"
)

// Defines values for GetHabilitationEnum.
const (
	Both    GetHabilitationEnum = "both"
	Indoor  GetHabilitationEnum = "indoor"
	Outside GetHabilitationEnum = "outside"
)

// Defines values for PetIconEnum.
const (
	ANTFARM      PetIconEnum = "ANT_FARM"
	AXOLOTL      PetIconEnum = "AXOLOTL"
	BEARDEDAGAMA PetIconEnum = "BEARDED_AGAMA"
	CANARY       PetIconEnum = "CANARY"
	CAT          PetIconEnum = "CAT"
	CHICKEN      PetIconEnum = "CHICKEN"
	CHINCHILLA   PetIconEnum = "CHINCHILLA"
	DOG          PetIconEnum = "DOG"
	DUCK         PetIconEnum = "DUCK"
	FERRET       PetIconEnum = "FERRET"
	FISH         PetIconEnum = "FISH"
	FROG         PetIconEnum = "FROG"
	GECKO        PetIconEnum = "GECKO"
	GUINEAPIG    PetIconEnum = "GUINEA_PIG"
	HAMSTER      PetIconEnum = "HAMSTER"
	HEDGEHOG     PetIconEnum = "HEDGEHOG"
	HERMITCRAB   PetIconEnum = "HERMIT_CRAB"
	IGUANA       PetIconEnum = "IGUANA"
	MINIGOAT     PetIconEnum = "MINI_GOAT"
	MINIPIG      PetIconEnum = "MINI_PIG"
	MOUSE        PetIconEnum = "MOUSE"
	OTHER        PetIconEnum = "OTHER"
	PARROT       PetIconEnum = "PARROT"
	PIGEON       PetIconEnum = "PIGEON"
	PYTHON       PetIconEnum = "PYTHON"
	RABBIT       PetIconEnum = "RABBIT"
	RAT          PetIconEnum = "RAT"
	SNAIL        PetIconEnum = "SNAIL"
	SNAKE        PetIconEnum = "SNAKE"
	TARANTULA    PetIconEnum = "TARANTULA"
	TURTLE       PetIconEnum = "TURTLE"
)

// Defines values for LanguageCode.
const (
	En LanguageCode = "en"
	Ru LanguageCode = "ru"
)

// ErrorCodeEnum Код ошибки для маппинга на фронте
type ErrorCodeEnum string

// GetActivitiesResponse defines model for GetActivitiesResponse.
type GetActivitiesResponse struct {
	Items   []ItemsArrayActivitiesModel `json:"items"`
	PetName string                      `json:"pet_name"`
}

// GetErrorResponse defines model for GetErrorResponse.
type GetErrorResponse struct {
	// Code Код ошибки для маппинга на фронте
	Code ErrorCodeEnum `json:"code"`

	// Message Техническое описание ошибки для отладки
	Message string `json:"message"`

	// Payload Произвольные дополнительные данные об ошибке
	Payload *interface{} `json:"payload,omitempty"`
}

// GetEventEnum defines model for GetEventEnum.
type GetEventEnum string

// GetEventIdResponseRequest defines model for GetEventIdResponseRequest.
type GetEventIdResponseRequest struct {
	Date    time.Time          `json:"date"`
	Id      openapi_types.UUID `json:"id"`
	Notes   *string            `json:"notes,omitempty"`
	PetId   openapi_types.UUID `json:"pet_id"`
	PetName string             `json:"pet_name"`
	Type    GetEventEnum       `json:"type"`
	Value   string             `json:"value"`
}

// GetEventRequest defines model for GetEventRequest.
type GetEventRequest struct {
	Date  time.Time          `json:"date"`
	Notes *string            `json:"notes,omitempty"`
	PetId openapi_types.UUID `json:"pet_id"`
	Type  GetEventEnum       `json:"type"`
	Value string             `json:"value"`
}

// GetEventResponse defines model for GetEventResponse.
type GetEventResponse struct {
	Date  time.Time          `json:"date"`
	Id    openapi_types.UUID `json:"id"`
	Notes *string            `json:"notes,omitempty"`
	Type  GetEventEnum       `json:"type"`
	Value string             `json:"value"`
}

// GetGenderEnum defines model for GetGenderEnum.
type GetGenderEnum string

// GetGuestRequest defines model for GetGuestRequest.
type GetGuestRequest struct {
	DeviceId string `json:"device_id"`
}

// GetHabilitationEnum defines model for GetHabilitationEnum.
type GetHabilitationEnum string

// GetLoginRequest defines model for GetLoginRequest.
type GetLoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// GetLoginResponse defines model for GetLoginResponse.
type GetLoginResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// GetMasterProfileResponse defines model for GetMasterProfileResponse.
type GetMasterProfileResponse struct {
	Email     *string `json:"email,omitempty"`
	FirstName string  `json:"first_name"`

	// Id Идентификатор пользователя (users.id), а не первичный ключ строки profile
	Id         openapi_types.UUID `json:"id"`
	LastName   *string            `json:"last_name,omitempty"`
	Login      string             `json:"login"`
	MiddleName *string            `json:"middle_name,omitempty"`
	Phone      *string            `json:"phone,omitempty"`
}

// GetPetProfileRequest defines model for GetPetProfileRequest.
type GetPetProfileRequest struct {
	BirthDate    *openapi_types.Date  `json:"birth_date,omitempty"`
	Breed        *string              `json:"breed,omitempty"`
	Color        *string              `json:"color,omitempty"`
	Gender       *GetGenderEnum       `json:"gender,omitempty"`
	Habilitation *GetHabilitationEnum `json:"habilitation,omitempty"`
	Name         string               `json:"name"`
	Notes        *string              `json:"notes,omitempty"`
	Species      string               `json:"species"`
	Sterilized   *bool                `json:"sterilized,omitempty"`
}

// GetPetProfileResponse defines model for GetPetProfileResponse.
type GetPetProfileResponse struct {
	BirthDate    *openapi_types.Date  `json:"birth_date,omitempty"`
	Breed        *string              `json:"breed,omitempty"`
	Color        *string              `json:"color,omitempty"`
	Gender       *GetGenderEnum       `json:"gender,omitempty"`
	Habilitation *GetHabilitationEnum `json:"habilitation,omitempty"`
	Icon         PetIconEnum          `json:"icon"`
	Id           openapi_types.UUID   `json:"id"`
	IsDeleted    *bool                `json:"is_deleted,omitempty"`
	Name         string               `json:"name"`
	Notes        *string              `json:"notes,omitempty"`
	Species      string               `json:"species"`
	Sterilized   *bool                `json:"sterilized,omitempty"`
}

// GetProfileRequest defines model for GetProfileRequest.
type GetProfileRequest struct {
	Email      *string `json:"email,omitempty"`
	FirstName  string  `json:"first_name"`
	LastName   *string `json:"last_name,omitempty"`
	MiddleName *string `json:"middle_name,omitempty"`
	Phone      *string `json:"phone,omitempty"`
}

// GetProfileUpdateRequest Частичное обновление профиля через PUT /profile: все поля необязательны, но должно быть передано хотя бы одно.
type GetProfileUpdateRequest struct {
	Email      *string `json:"email,omitempty"`
	FirstName  *string `json:"first_name,omitempty"`
	LastName   *string `json:"last_name,omitempty"`
	MiddleName *string `json:"middle_name,omitempty"`
	Phone      *string `json:"phone,omitempty"`
}

// GetRefreshRequest defines model for GetRefreshRequest.
type GetRefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// GetShortInfoAllPetResponse defines model for GetShortInfoAllPetResponse.
type GetShortInfoAllPetResponse struct {
	Items []GetShortInfoPetResponse `json:"items"`
}

// GetShortInfoPetResponse defines model for GetShortInfoPetResponse.
type GetShortInfoPetResponse struct {
	Breed   string             `json:"breed"`
	Icon    PetIconEnum        `json:"icon"`
	Id      openapi_types.UUID `json:"id"`
	Name    string             `json:"name"`
	Species string             `json:"species"`
}

// ItemsArrayActivitiesModel defines model for ItemsArrayActivitiesModel.
type ItemsArrayActivitiesModel struct {
	Date   openapi_types.Date `json:"date"`
	Events []GetEventResponse `json:"events"`
}

// PetIconEnum defines model for PetIconEnum.
type PetIconEnum string

// UpdateEventRequest defines model for UpdateEventRequest.
type UpdateEventRequest struct {
	Date  *time.Time         `json:"date,omitempty"`
	Notes *string            `json:"notes,omitempty"`
	PetId openapi_types.UUID `json:"pet_id"`
	Type  *GetEventEnum      `json:"type,omitempty"`
	Value *string            `json:"value,omitempty"`
}

// UpdatePetProfileRequest defines model for UpdatePetProfileRequest.
type UpdatePetProfileRequest struct {
	BirthDate    *openapi_types.Date  `json:"birth_date,omitempty"`
	Breed        *string              `json:"breed,omitempty"`
	Color        *string              `json:"color,omitempty"`
	Gender       *GetGenderEnum       `json:"gender,omitempty"`
	Habilitation *GetHabilitationEnum `json:"habilitation,omitempty"`
	Name         *string              `json:"name,omitempty"`
	Notes        *string              `json:"notes,omitempty"`
	Species      *string              `json:"species,omitempty"`
	Sterilized   *bool                `json:"sterilized,omitempty"`
}

// LanguageCode defines model for LanguageCode.
type LanguageCode string

// GetActivitiesParams defines parameters for GetActivities.
type GetActivitiesParams struct {
	PetId openapi_types.UUID `form:"pet_id" json:"pet_id"`
	From  openapi_types.Date `form:"from" json:"from"`
	To    openapi_types.Date `form:"to" json:"to"`
}

// PostGuestJSONRequestBody defines body for PostGuest for application/json ContentType.
type PostGuestJSONRequestBody = GetGuestRequest

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = GetLoginRequest

// PostLogoutJSONRequestBody defines body for PostLogout for application/json ContentType.
type PostLogoutJSONRequestBody = GetRefreshRequest

// PostRefreshJSONRequestBody defines body for PostRefresh for application/json ContentType.
type PostRefreshJSONRequestBody = GetRefreshRequest

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody = GetLoginRequest

// PostEventJSONRequestBody defines body for PostEvent for application/json ContentType.
type PostEventJSONRequestBody = GetEventRequest

// PatchEventJSONRequestBody defines body for PatchEvent for application/json ContentType.
type PatchEventJSONRequestBody = UpdateEventRequest

// PostPetJSONRequestBody defines body for PostPet for application/json ContentType.
type PostPetJSONRequestBody = GetPetProfileRequest

// PutPetJSONRequestBody defines body for PutPet for application/json ContentType.
type PutPetJSONRequestBody = UpdatePetProfileRequest

// PostProfileJSONRequestBody defines body for PostProfile for application/json ContentType.
type PostProfileJSONRequestBody = GetProfileRequest

// PutProfileJSONRequestBody defines body for PutProfile for application/json ContentType.
type PutProfileJSONRequestBody = GetProfileUpdateRequest
