// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AuthorizationScopes = "Authorization.Scopes"
)

// Defines values for AllergySeverityEnum.
const (
	Mild     AllergySeverityEnum = "mild"
	Moderate AllergySeverityEnum = "moderate"
	Severe   AllergySeverityEnum = "severe"
)

// Defines values for DiseaseStatusEnum.
const (
	Active DiseaseStatusEnum = "active"
	Cured  DiseaseStatusEnum = "cured"
)

// Defines values for ErrorCodeEnum.
const (
	BADREQUEST      ErrorCodeEnum = "BAD_REQUEST"
	CONFLICT        ErrorCodeEnum = "CONFLICT"
	FORBIDDEN       ErrorCodeEnum = "FORBIDDEN"
	INTERNALERROR   ErrorCodeEnum = "INTERNAL_ERROR"
	NOTFOUND        ErrorCodeEnum = "NOT_FOUND"
	RATELIMITED     ErrorCodeEnum = "RATE_LIMITED"
	UNAUTHORIZED    ErrorCodeEnum = "UNAUTHORIZED"
	VALIDATIONERROR ErrorCodeEnum = "VALIDATION_ERROR"
)

// Defines values for EventActivityKindEnum.
const (
	EventActivityKindEnumFreeRange EventActivityKindEnum = "free_range"
	EventActivityKindEnumOther     EventActivityKindEnum = "other"
	EventActivityKindEnumPlay      EventActivityKindEnum = "play"
	EventActivityKindEnumSwim      EventActivityKindEnum = "swim"
	EventActivityKindEnumTraining  EventActivityKindEnum = "training"
	EventActivityKindEnumWalk      EventActivityKindEnum = "walk"
)

// Defines values for EventExcretionStatusEnum.
const (
	EventExcretionStatusEnumAbnormal EventExcretionStatusEnum = "abnormal"
	EventExcretionStatusEnumNormal   EventExcretionStatusEnum = "normal"
)

// Defines values for EventFeedingFoodEnum.
const (
	EventFeedingFoodEnumDry        EventFeedingFoodEnum = "dry"
	EventFeedingFoodEnumFrozenPrey EventFeedingFoodEnum = "frozen_prey"
	EventFeedingFoodEnumGrain      EventFeedingFoodEnum = "grain"
	EventFeedingFoodEnumGreens     EventFeedingFoodEnum = "greens"
	EventFeedingFoodEnumHay        EventFeedingFoodEnum = "hay"
	EventFeedingFoodEnumHomemade   EventFeedingFoodEnum = "homemade"
	EventFeedingFoodEnumInsects    EventFeedingFoodEnum = "insects"
	EventFeedingFoodEnumLivePrey   EventFeedingFoodEnum = "live_prey"
	EventFeedingFoodEnumOther      EventFeedingFoodEnum = "other"
	EventFeedingFoodEnumRaw        EventFeedingFoodEnum = "raw"
	EventFeedingFoodEnumTreat      EventFeedingFoodEnum = "treat"
	EventFeedingFoodEnumWet        EventFeedingFoodEnum = "wet"
)

// Defines values for EventFeedingUnitEnum.
const (
	EventFeedingUnitEnumG       EventFeedingUnitEnum = "g"
	EventFeedingUnitEnumMl      EventFeedingUnitEnum = "ml"
	EventFeedingUnitEnumPiece   EventFeedingUnitEnum = "piece"
	EventFeedingUnitEnumPortion EventFeedingUnitEnum = "portion"
)

// Defines values for EventHygieneProcedureEnum.
const (
	EventHygieneProcedureEnumAntiparasitic EventHygieneProcedureEnum = "antiparasitic"
	EventHygieneProcedureEnumBath          EventHygieneProcedureEnum = "bath"
	EventHygieneProcedureEnumBeak          EventHygieneProcedureEnum = "beak"
	EventHygieneProcedureEnumBrushing      EventHygieneProcedureEnum = "brushing"
	EventHygieneProcedureEnumEars          EventHygieneProcedureEnum = "ears"
	EventHygieneProcedureEnumEnclosure     EventHygieneProcedureEnum = "enclosure"
	EventHygieneProcedureEnumNails         EventHygieneProcedureEnum = "nails"
	EventHygieneProcedureEnumOther         EventHygieneProcedureEnum = "other"
	EventHygieneProcedureEnumShedding      EventHygieneProcedureEnum = "shedding"
	EventHygieneProcedureEnumTeeth         EventHygieneProcedureEnum = "teeth"
	EventHygieneProcedureEnumWaterChange   EventHygieneProcedureEnum = "water_change"
)

// Defines values for EventMedicationDoseUnitEnum.
const (
	EventMedicationDoseUnitEnumCapsule EventMedicationDoseUnitEnum = "capsule"
	EventMedicationDoseUnitEnumDrop    EventMedicationDoseUnitEnum = "drop"
	EventMedicationDoseUnitEnumG       EventMedicationDoseUnitEnum = "g"
	EventMedicationDoseUnitEnumMcg     EventMedicationDoseUnitEnum = "mcg"
	EventMedicationDoseUnitEnumMg      EventMedicationDoseUnitEnum = "mg"
	EventMedicationDoseUnitEnumMl      EventMedicationDoseUnitEnum = "ml"
	EventMedicationDoseUnitEnumTablet  EventMedicationDoseUnitEnum = "tablet"
)

// Defines values for EventMoodStateEnum.
const (
	Aggressive EventMoodStateEnum = "aggressive"
	Anxious    EventMoodStateEnum = "anxious"
	Calm       EventMoodStateEnum = "calm"
	Hiding     EventMoodStateEnum = "hiding"
	Lethargic  EventMoodStateEnum = "lethargic"
	Playful    EventMoodStateEnum = "playful"
)

// Defines values for EventStatsAggregationEnum.
const (
	Avg   EventStatsAggregationEnum = "avg"
	Count EventStatsAggregationEnum = "count"
	Last  EventStatsAggregationEnum = "last"
	Sum   EventStatsAggregationEnum = "sum"
)

// Defines values for EventStatsBucketEnum.
const (
	Day   EventStatsBucketEnum = "day"
	Month EventStatsBucketEnum = "month"
	Week  EventStatsBucketEnum = "week"
)

// Defines values for EventStatsValueKindEnum.
const (
	Category EventStatsValueKindEnum = "category"
	Measure  EventStatsValueKindEnum = "measure"
	Quantity EventStatsValueKindEnum = "quantity"
)

// Defines values for EventTemperatureKindEnum.
const (
	Body        EventTemperatureKindEnum = "body"
	Environment EventTemperatureKindEnum = "environment"
)

// Defines values for GetEventEnum.
const (
	GetEventEnumActivity    GetEventEnum = "activity"
	GetEventEnumDefecation  GetEventEnum = "defecation"
	GetEventEnumDiarrhea    GetEventEnum = "diarrhea"
	GetEventEnumFeeding     GetEventEnum = "feeding"
	GetEventEnumHygiene     GetEventEnum = "hygiene"
	GetEventEnumMedication  GetEventEnum = "medication"
	GetEventEnumMood        GetEventEnum = "mood"
	GetEventEnumOther       GetEventEnum = "other"
	GetEventEnumSleep       GetEventEnum = "sleep"
	GetEventEnumTemperature GetEventEnum = "temperature"
	GetEventEnumUrine       GetEventEnum = "urine"
	GetEventEnumVomit       GetEventEnum = "vomit"
	GetEventEnumWater       GetEventEnum = "water"
	GetEventEnumWeight      GetEventEnum = "weight"
)

// Defines values for GetGenderEnum.
const (
	Female GetGenderEnum = "female"
	Male   GetGenderEnum = "male"
	Other  GetGenderEnum = "other"
)

// Defines values for GetHabilitationEnum.
const (
	Both    GetHabilitationEnum = "both"
	Indoor  GetHabilitationEnum = "indoor"
	Outside GetHabilitationEnum = "outside"
)

// Defines values for MedicationFrequencyTypeEnum.
const (
	AsNeeded     MedicationFrequencyTypeEnum = "as_needed"
	Daily        MedicationFrequencyTypeEnum = "daily"
	EveryNDays   MedicationFrequencyTypeEnum = "every_n_days"
	SpecificDays MedicationFrequencyTypeEnum = "specific_days"
)

// Defines values for PetBodyConditionEnum.
const (
	PetBodyConditionEnumNormal      PetBodyConditionEnum = "normal"
	PetBodyConditionEnumObese       PetBodyConditionEnum = "obese"
	PetBodyConditionEnumOverweight  PetBodyConditionEnum = "overweight"
	PetBodyConditionEnumThin        PetBodyConditionEnum = "thin"
	PetBodyConditionEnumUnderweight PetBodyConditionEnum = "underweight"
)

// Defines values for PetIconEnum.
const (
	ANTFARM      PetIconEnum = "ANT_FARM"
	AXOLOTL      PetIconEnum = "AXOLOTL"
	BEARDEDAGAMA PetIconEnum = "BEARDED_AGAMA"
	CANARY       PetIconEnum = "CANARY"
	CAT          PetIconEnum = "CAT"
	CHICKEN      PetIconEnum = "CHICKEN"
	CHINCHILLA   PetIconEnum = "CHINCHILLA"
	DOG          PetIconEnum = "DOG"
	DUCK         PetIconEnum = "DUCK"
	FERRET       PetIconEnum = "FERRET"
	FISH         PetIconEnum = "FISH"
	FROG         PetIconEnum = "FROG"
	GECKO        PetIconEnum = "GECKO"
	GUINEAPIG    PetIconEnum = "GUINEA_PIG"
	HAMSTER      PetIconEnum = "HAMSTER"
	HEDGEHOG     PetIconEnum = "HEDGEHOG"
	HERMITCRAB   PetIconEnum = "HERMIT_CRAB"
	IGUANA       PetIconEnum = "IGUANA"
	MINIGOAT     PetIconEnum = "MINI_GOAT"
	MINIPIG      PetIconEnum = "MINI_PIG"
	MOUSE        PetIconEnum = "MOUSE"
	OTHER        PetIconEnum = "OTHER"
	PARROT       PetIconEnum = "PARROT"
	PIGEON       PetIconEnum = "PIGEON"
	PYTHON       PetIconEnum = "PYTHON"
	RABBIT       PetIconEnum = "RABBIT"
	RAT          PetIconEnum = "RAT"
	SNAIL        PetIconEnum = "SNAIL"
	SNAKE        PetIconEnum = "SNAKE"
	TARANTULA    PetIconEnum = "TARANTULA"
	TURTLE       PetIconEnum = "TURTLE"
)

// Defines values for LanguageCode.
const (
	En LanguageCode = "en"
	Ru LanguageCode = "ru"
)

// ActivitiesCalendarItem defines model for ActivitiesCalendarItem.
type ActivitiesCalendarItem struct {
	Count int                `json:"count"`
	Date  openapi_types.Date `json:"date"`
}

// ActivitiesDayEventItem defines model for ActivitiesDayEventItem.
type ActivitiesDayEventItem struct {
	Date       time.Time          `json:"date"`
	FilesCount int                `json:"files_count"`
	Id         openapi_types.UUID `json:"id"`
	Notes      *string            `json:"notes,omitempty"`
	PetId      openapi_types.UUID `json:"pet_id"`
	PetName    string             `json:"pet_name"`
	Type       GetEventEnum       `json:"type"`

	// Value Типизированное значение события. Состав полей определяется полем type события (размеченное объединение, дискриминатор — type; см. требование «Модель значения события и реестр метрик»). На уровне схемы перечислены все возможные поля; обязательность, диапазоны и допустимость поля для конкретного type проверяются сервером по единому реестру метрик. Поле, не описанное формой value для данного type, даёт 400, а не игнорируется молча.
	//
	// Состав по типам:
	// * weight — amount (кг, 0.001–400)
	// * temperature — amount (°C, 0–50), kind (EventTemperatureKindEnum)
	// * feeding — amount (0.01–5000), unit, food
	// * water — amount (мл, 0.1–5000)
	// * activity — duration_min (1–1440), kind (EventActivityKindEnum), distance_m (0–100000, опционально)
	// * sleep — duration_min (1–1440)
	// * medication — name (1–100), dose_amount (0.001–10000) и dose_unit — только вместе, опционально
	// * hygiene — procedure
	// * mood — state
	// * urine, defecation, vomit, diarrhea — status
	// * other — label (1–50)
	Value EventValue `json:"value"`
}

// AllergySeverityEnum defines model for AllergySeverityEnum.
type AllergySeverityEnum string

// DiseaseStatusEnum defines model for DiseaseStatusEnum.
type DiseaseStatusEnum string

// ErrorCodeEnum Код ошибки для маппинга на фронте
type ErrorCodeEnum string

// EventActivityKindEnum Вид активности (value.kind при type=activity). free_range — время вне клетки, вольера или террариума.
type EventActivityKindEnum string

// EventExcretionStatusEnum Статус выделений (value.status при type=urine|defecation|vomit|diarrhea).
type EventExcretionStatusEnum string

// EventFeedingFoodEnum Вид корма (value.food при type=feeding).
type EventFeedingFoodEnum string

// EventFeedingUnitEnum Единица измерения кормления (value.unit при type=feeding). piece — счётные корма (кормовые грызуны, насекомые, мальки).
type EventFeedingUnitEnum string

// EventFile defines model for EventFile.
type EventFile struct {
	ContentType string             `json:"content_type"`
	FileId      openapi_types.UUID `json:"file_id"`

	// Filename null для фотографий и для документов без переданного имени.
	Filename *string `json:"filename"`

	// Url Presigned GET URL — временная ссылка, не постоянный адрес.
	Url string `json:"url"`
}

// EventHygieneProcedureEnum Процедура гигиены (value.procedure при type=hygiene).
type EventHygieneProcedureEnum string

// EventMedicationDoseUnitEnum Единица дозы лекарства (value.dose_unit при type=medication).
type EventMedicationDoseUnitEnum string

// EventMoodStateEnum Состояние питомца (value.state при type=mood).
type EventMoodStateEnum string

// EventStatsAggregationEnum Способ свёртки значений метрики внутри интервала, применённый к этой серии.
type EventStatsAggregationEnum string

// EventStatsBucket defines model for EventStatsBucket.
type EventStatsBucket struct {
	// BucketStart Дата начала интервала (UTC).
	BucketStart openapi_types.Date `json:"bucket_start"`

	// Count Количество событий, попавших в интервал.
	Count int `json:"count"`

	// Value Агрегированное значение интервала; null — событий в интервале не было.
	Value *float32 `json:"value"`
}

// EventStatsBucketEnum Интервал агрегации графика. week — календарная неделя по UTC с понедельника, month — календарный месяц по UTC.
type EventStatsBucketEnum string

// EventStatsSeries defines model for EventStatsSeries.
type EventStatsSeries struct {
	// Aggregation Способ свёртки значений метрики внутри интервала, применённый к этой серии.
	Aggregation EventStatsAggregationEnum `json:"aggregation"`

	// Buckets Точки серии по интервалам, по возрастанию bucket_start. Интервалы без событий присутствуют с value=null и count=0.
	Buckets []EventStatsBucket `json:"buckets"`

	// Category Значение, разделяющее серии одного типа: при value_kind=category — конкретное значение категории (procedure, state, status); при type=temperature — вид замера (EventTemperatureKindEnum). Отсутствует, если тип даёт одну серию.
	Category *string `json:"category,omitempty"`

	// Metric Ключ метрики из реестра метрик (например amount_avg, amount_last, amount_sum, duration_min_sum, distance_m_sum, count).
	Metric string       `json:"metric"`
	Type   GetEventEnum `json:"type"`

	// Unit Единица измерения значений серии; отсутствует, если у метрики нет единицы (категориальные серии, количество приёмов).
	Unit *string `json:"unit,omitempty"`

	// ValueKind Характер значения серии; определяет форму графика на клиенте. Тип с value_kind=label (other) не агрегируется и в ответе не встречается.
	ValueKind EventStatsValueKindEnum `json:"value_kind"`
}

// EventStatsValueKindEnum Характер значения серии; определяет форму графика на клиенте. Тип с value_kind=label (other) не агрегируется и в ответе не встречается.
type EventStatsValueKindEnum string

// EventTemperatureKindEnum Вид замера температуры (value.kind при type=temperature): body — температура тела, environment — температура среды обитания (террариум, точка прогрева, вода аквариума).
type EventTemperatureKindEnum string

// EventValue Типизированное значение события. Состав полей определяется полем type события (размеченное объединение, дискриминатор — type; см. требование «Модель значения события и реестр метрик»). На уровне схемы перечислены все возможные поля; обязательность, диапазоны и допустимость поля для конкретного type проверяются сервером по единому реестру метрик. Поле, не описанное формой value для данного type, даёт 400, а не игнорируется молча.
//
// Состав по типам:
// * weight — amount (кг, 0.001–400)
// * temperature — amount (°C, 0–50), kind (EventTemperatureKindEnum)
// * feeding — amount (0.01–5000), unit, food
// * water — amount (мл, 0.1–5000)
// * activity — duration_min (1–1440), kind (EventActivityKindEnum), distance_m (0–100000, опционально)
// * sleep — duration_min (1–1440)
// * medication — name (1–100), dose_amount (0.001–10000) и dose_unit — только вместе, опционально
// * hygiene — procedure
// * mood — state
// * urine, defecation, vomit, diarrhea — status
// * other — label (1–50)
type EventValue struct {
	// Amount Числовая величина: weight (кг), temperature (°C), feeding (в единице unit), water (мл).
	Amount *float32 `json:"amount,omitempty"`

	// DistanceM Дистанция в метрах (type=activity, опционально).
	DistanceM *float32 `json:"distance_m,omitempty"`

	// DoseAmount Доза препарата в единице dose_unit (type=medication, только вместе с dose_unit).
	DoseAmount *float32 `json:"dose_amount,omitempty"`

	// DoseUnit Единица дозы лекарства (value.dose_unit при type=medication).
	DoseUnit *EventMedicationDoseUnitEnum `json:"dose_unit,omitempty"`

	// DurationMin Длительность в минутах: activity, sleep.
	DurationMin *float32 `json:"duration_min,omitempty"`

	// Food Вид корма (value.food при type=feeding).
	Food *EventFeedingFoodEnum `json:"food,omitempty"`

	// Kind Вид наблюдения: при type=temperature — значение EventTemperatureKindEnum, при type=activity — значение EventActivityKindEnum.
	Kind *string `json:"kind,omitempty"`

	// Label Краткое обозначение события (type=other); подробности — в notes.
	Label *string `json:"label,omitempty"`

	// Name Название препарата (type=medication).
	Name *string `json:"name,omitempty"`

	// Procedure Процедура гигиены (value.procedure при type=hygiene).
	Procedure *EventHygieneProcedureEnum `json:"procedure,omitempty"`

	// State Состояние питомца (value.state при type=mood).
	State *EventMoodStateEnum `json:"state,omitempty"`

	// Status Статус выделений (value.status при type=urine|defecation|vomit|diarrhea).
	Status *EventExcretionStatusEnum `json:"status,omitempty"`

	// Unit Единица измерения кормления (value.unit при type=feeding). piece — счётные корма (кормовые грызуны, насекомые, мальки).
	Unit *EventFeedingUnitEnum `json:"unit,omitempty"`
}

// GetActivitiesCalendarResponse defines model for GetActivitiesCalendarResponse.
type GetActivitiesCalendarResponse struct {
	Items []ActivitiesCalendarItem `json:"items"`
}

// GetActivitiesDayResponse defines model for GetActivitiesDayResponse.
type GetActivitiesDayResponse struct {
	Date  openapi_types.Date       `json:"date"`
	Items []ActivitiesDayEventItem `json:"items"`
}

// GetActivitiesResponse defines model for GetActivitiesResponse.
type GetActivitiesResponse struct {
	Items   []ItemsArrayActivitiesModel `json:"items"`
	PetName string                      `json:"pet_name"`
}

// GetAllergyIdResponseRequest defines model for GetAllergyIdResponseRequest.
type GetAllergyIdResponseRequest struct {
	Id openapi_types.UUID `json:"id"`
}

// GetAllergyRequest defines model for GetAllergyRequest.
type GetAllergyRequest struct {
	Allergen     string              `json:"allergen"`
	DetectedDate *openapi_types.Date `json:"detected_date"`
	Note         *string             `json:"note"`
	Reaction     *string             `json:"reaction"`
	Severity     AllergySeverityEnum `json:"severity"`
}

// GetAllergyResponse defines model for GetAllergyResponse.
type GetAllergyResponse struct {
	Allergen     string              `json:"allergen"`
	DetectedDate *openapi_types.Date `json:"detected_date"`

	// FilesCount Количество прикреплённых файлов аллергии (0, если файлов нет).
	FilesCount int                 `json:"files_count"`
	Id         openapi_types.UUID  `json:"id"`
	Note       *string             `json:"note"`
	PetId      openapi_types.UUID  `json:"pet_id"`
	Reaction   *string             `json:"reaction"`
	Severity   AllergySeverityEnum `json:"severity"`
}

// GetDiseaseIdResponseRequest defines model for GetDiseaseIdResponseRequest.
type GetDiseaseIdResponseRequest struct {
	Id openapi_types.UUID `json:"id"`
}

// GetDiseaseRequest defines model for GetDiseaseRequest.
type GetDiseaseRequest struct {
	DiagnosedDate openapi_types.Date `json:"diagnosed_date"`
	Name          string             `json:"name"`
	Note          *string            `json:"note"`
	Status        DiseaseStatusEnum  `json:"status"`
}

// GetDiseaseResponse defines model for GetDiseaseResponse.
type GetDiseaseResponse struct {
	DiagnosedDate openapi_types.Date `json:"diagnosed_date"`

	// FilesCount Количество прикреплённых файлов заболевания (0, если файлов нет).
	FilesCount int                `json:"files_count"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	Note       *string            `json:"note"`
	PetId      openapi_types.UUID `json:"pet_id"`
	Status     DiseaseStatusEnum  `json:"status"`
}

// GetErrorResponse defines model for GetErrorResponse.
type GetErrorResponse struct {
	// Code Код ошибки для маппинга на фронте
	Code ErrorCodeEnum `json:"code"`

	// Message Техническое описание ошибки для отладки
	Message string `json:"message"`

	// Payload Произвольные дополнительные данные об ошибке
	Payload *interface{} `json:"payload,omitempty"`
}

// GetEventEnum defines model for GetEventEnum.
type GetEventEnum string

// GetEventIdResponseRequest defines model for GetEventIdResponseRequest.
type GetEventIdResponseRequest struct {
	Date time.Time `json:"date"`

	// Files Прикреплённые файлы события (фото и документы), в порядке position.
	Files   []EventFile        `json:"files"`
	Id      openapi_types.UUID `json:"id"`
	Notes   *string            `json:"notes,omitempty"`
	PetId   openapi_types.UUID `json:"pet_id"`
	PetName string             `json:"pet_name"`
	Type    GetEventEnum       `json:"type"`

	// Value Типизированное значение события. Состав полей определяется полем type события (размеченное объединение, дискриминатор — type; см. требование «Модель значения события и реестр метрик»). На уровне схемы перечислены все возможные поля; обязательность, диапазоны и допустимость поля для конкретного type проверяются сервером по единому реестру метрик. Поле, не описанное формой value для данного type, даёт 400, а не игнорируется молча.
	//
	// Состав по типам:
	// * weight — amount (кг, 0.001–400)
	// * temperature — amount (°C, 0–50), kind (EventTemperatureKindEnum)
	// * feeding — amount (0.01–5000), unit, food
	// * water — amount (мл, 0.1–5000)
	// * activity — duration_min (1–1440), kind (EventActivityKindEnum), distance_m (0–100000, опционально)
	// * sleep — duration_min (1–1440)
	// * medication — name (1–100), dose_amount (0.001–10000) и dose_unit — только вместе, опционально
	// * hygiene — procedure
	// * mood — state
	// * urine, defecation, vomit, diarrhea — status
	// * other — label (1–50)
	Value EventValue `json:"value"`
}

// GetEventRequest defines model for GetEventRequest.
type GetEventRequest struct {
	Date  time.Time          `json:"date"`
	Notes *string            `json:"notes,omitempty"`
	PetId openapi_types.UUID `json:"pet_id"`
	Type  GetEventEnum       `json:"type"`

	// Value Типизированное значение события. Состав полей определяется полем type события (размеченное объединение, дискриминатор — type; см. требование «Модель значения события и реестр метрик»). На уровне схемы перечислены все возможные поля; обязательность, диапазоны и допустимость поля для конкретного type проверяются сервером по единому реестру метрик. Поле, не описанное формой value для данного type, даёт 400, а не игнорируется молча.
	//
	// Состав по типам:
	// * weight — amount (кг, 0.001–400)
	// * temperature — amount (°C, 0–50), kind (EventTemperatureKindEnum)
	// * feeding — amount (0.01–5000), unit, food
	// * water — amount (мл, 0.1–5000)
	// * activity — duration_min (1–1440), kind (EventActivityKindEnum), distance_m (0–100000, опционально)
	// * sleep — duration_min (1–1440)
	// * medication — name (1–100), dose_amount (0.001–10000) и dose_unit — только вместе, опционально
	// * hygiene — procedure
	// * mood — state
	// * urine, defecation, vomit, diarrhea — status
	// * other — label (1–50)
	Value EventValue `json:"value"`
}

// GetEventResponse defines model for GetEventResponse.
type GetEventResponse struct {
	Date time.Time `json:"date"`

	// FilesCount Количество прикреплённых файлов события (0, если файлов нет).
	FilesCount int                `json:"files_count"`
	Id         openapi_types.UUID `json:"id"`
	Notes      *string            `json:"notes,omitempty"`
	Type       GetEventEnum       `json:"type"`

	// Value Типизированное значение события. Состав полей определяется полем type события (размеченное объединение, дискриминатор — type; см. требование «Модель значения события и реестр метрик»). На уровне схемы перечислены все возможные поля; обязательность, диапазоны и допустимость поля для конкретного type проверяются сервером по единому реестру метрик. Поле, не описанное формой value для данного type, даёт 400, а не игнорируется молча.
	//
	// Состав по типам:
	// * weight — amount (кг, 0.001–400)
	// * temperature — amount (°C, 0–50), kind (EventTemperatureKindEnum)
	// * feeding — amount (0.01–5000), unit, food
	// * water — amount (мл, 0.1–5000)
	// * activity — duration_min (1–1440), kind (EventActivityKindEnum), distance_m (0–100000, опционально)
	// * sleep — duration_min (1–1440)
	// * medication — name (1–100), dose_amount (0.001–10000) и dose_unit — только вместе, опционально
	// * hygiene — procedure
	// * mood — state
	// * urine, defecation, vomit, diarrhea — status
	// * other — label (1–50)
	Value EventValue `json:"value"`
}

// GetEventStatsResponse defines model for GetEventStatsResponse.
type GetEventStatsResponse struct {
	PetName string             `json:"pet_name"`
	Series  []EventStatsSeries `json:"series"`
}

// GetGenderEnum defines model for GetGenderEnum.
type GetGenderEnum string

// GetGuestRequest defines model for GetGuestRequest.
type GetGuestRequest struct {
	DeviceId string `json:"device_id"`
}

// GetHabilitationEnum defines model for GetHabilitationEnum.
type GetHabilitationEnum string

// GetLoginRequest defines model for GetLoginRequest.
type GetLoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// GetLoginResponse defines model for GetLoginResponse.
type GetLoginResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// GetMasterProfileResponse defines model for GetMasterProfileResponse.
type GetMasterProfileResponse struct {
	Email     *string `json:"email"`
	FirstName string  `json:"first_name"`

	// Id Идентификатор пользователя (users.id), а не первичный ключ строки profile
	Id         openapi_types.UUID `json:"id"`
	LastName   *string            `json:"last_name"`
	Login      string             `json:"login"`
	MiddleName *string            `json:"middle_name"`
	Phone      *string            `json:"phone"`
}

// GetMedicationIdResponseRequest defines model for GetMedicationIdResponseRequest.
type GetMedicationIdResponseRequest struct {
	Id openapi_types.UUID `json:"id"`
}

// GetMedicationRequest defines model for GetMedicationRequest.
type GetMedicationRequest struct {
	// AddEvent Создать набор событий-напоминаний сразу при создании курса. Недопустимо при frequency_type=as_needed.
	AddEvent *bool               `json:"add_event,omitempty"`
	Dosage   string              `json:"dosage"`
	EndDate  *openapi_types.Date `json:"end_date"`

	// FrequencyType Вид частоты приёма лекарства (по образцу раздела «Лекарства» Apple Health).
	FrequencyType MedicationFrequencyTypeEnum `json:"frequency_type"`
	IntervalDays  *int                        `json:"interval_days"`
	Name          string                      `json:"name"`
	Note          *string                     `json:"note"`
	StartDate     *openapi_types.Date         `json:"start_date"`
	Times         *[]MedicationTimeSlot       `json:"times"`
	Weekdays      *[]int                      `json:"weekdays"`
}

// GetMedicationResponse defines model for GetMedicationResponse.
type GetMedicationResponse struct {
	// Dosage Базовая дозировка в свободной форме, например «1 таблетка» или «5 мл»; используется по умолчанию для времён приёма без собственного dose_note.
	Dosage string `json:"dosage"`

	// EndDate Дата окончания курса; null = без даты окончания (бессрочно). Всегда null при frequency_type=as_needed.
	EndDate *openapi_types.Date `json:"end_date"`

	// EventIds id уже созданных событий приёма препарата, в порядке дат приёма. Заполняется через POST /medications/{id}/events.
	EventIds []openapi_types.UUID `json:"event_ids"`

	// FilesCount Количество прикреплённых файлов курса лечения (0, если файлов нет).
	FilesCount int `json:"files_count"`

	// FrequencyType Вид частоты приёма лекарства (по образцу раздела «Лекарства» Apple Health).
	FrequencyType MedicationFrequencyTypeEnum `json:"frequency_type"`
	Id            openapi_types.UUID          `json:"id"`

	// IntervalDays Интервал в днях, только при frequency_type=every_n_days, иначе null.
	IntervalDays *int   `json:"interval_days"`
	Name         string `json:"name"`

	// NextDose Минимальный момент (дата+время) расписания курса, который >= текущего момента, вычисленный по текущим frequency_type/weekdays/interval_days/times/start_date/end_date независимо от того, создан ли набор событий (event_ids). null при frequency_type=as_needed или если весь расчитанный график уже в прошлом.
	NextDose *time.Time         `json:"next_dose"`
	Note     *string            `json:"note"`
	PetId    openapi_types.UUID `json:"pet_id"`

	// StartDate Обязателен при frequency_type!=as_needed, иначе null.
	StartDate *openapi_types.Date `json:"start_date"`

	// Times Времена приёма в день, только при frequency_type!=as_needed, иначе null.
	Times *[]MedicationTimeSlot `json:"times"`

	// Weekdays Дни недели приёма (пн=1..вс=7), только при frequency_type=specific_days, иначе null.
	Weekdays *[]int `json:"weekdays"`
}

// GetPetProfileRequest defines model for GetPetProfileRequest.
type GetPetProfileRequest struct {
	BirthDate *openapi_types.Date `json:"birth_date,omitempty"`

	// BodyCondition Кондиция тела питомца (body condition score), вычисляется/задаётся вручную, хранится как поле питомца.
	BodyCondition *PetBodyConditionEnum `json:"body_condition,omitempty"`
	Breed         *string               `json:"breed,omitempty"`
	Color         *string               `json:"color,omitempty"`
	Gender        *GetGenderEnum        `json:"gender,omitempty"`
	Habitation    *GetHabilitationEnum  `json:"habitation,omitempty"`
	Name          string                `json:"name"`
	Notes         *string               `json:"notes,omitempty"`
	Species       string                `json:"species"`
	Sterilized    *bool                 `json:"sterilized,omitempty"`

	// Weight Вес питомца в кг (0.001–400), опционально. Не сохраняется как поле питомца — при передаче сервер создаёт событие типа weight со значением amount=weight.
	Weight *float32 `json:"weight,omitempty"`
}

// GetPetProfileResponse defines model for GetPetProfileResponse.
type GetPetProfileResponse struct {
	BirthDate *openapi_types.Date `json:"birth_date,omitempty"`

	// BodyCondition Кондиция тела питомца (body condition score), вычисляется/задаётся вручную, хранится как поле питомца.
	BodyCondition *PetBodyConditionEnum `json:"body_condition,omitempty"`
	Breed         *string               `json:"breed,omitempty"`
	Color         *string               `json:"color"`
	Gender        *GetGenderEnum        `json:"gender,omitempty"`
	Habitation    *GetHabilitationEnum  `json:"habitation,omitempty"`
	Icon          PetIconEnum           `json:"icon"`
	Id            openapi_types.UUID    `json:"id"`
	IsDeleted     *bool                 `json:"is_deleted,omitempty"`
	Name          string                `json:"name"`
	Notes         *string               `json:"notes"`

	// PhotoFileId id файла фотографии для DELETE /files/{file_id}; null если фотографии нет
	PhotoFileId *openapi_types.UUID `json:"photo_file_id"`

	// PhotoUrl Presigned GET URL на текущую фотографию питомца, временная ссылка с TTL; null если фотографии нет
	PhotoUrl   *string `json:"photo_url"`
	Species    string  `json:"species"`
	Sterilized *bool   `json:"sterilized,omitempty"`

	// Weight Текущий вес питомца в кг, вычисляется как amount последнего по date_time события типа weight; null если таких событий нет. Не хранится как отдельное поле питомца.
	Weight *float32 `json:"weight"`
}

// GetProfileRequest defines model for GetProfileRequest.
type GetProfileRequest struct {
	Email      *openapi_types.Email `json:"email,omitempty"`
	FirstName  string               `json:"first_name"`
	LastName   *string              `json:"last_name,omitempty"`
	MiddleName *string              `json:"middle_name,omitempty"`
	Phone      *string              `json:"phone,omitempty"`
}

// GetProfileUpdateRequest Частичное обновление профиля через PUT /profile: все поля необязательны, но должно быть передано хотя бы одно. Если первое имя (first_name) передано явно, оно не может быть пустой строкой.
type GetProfileUpdateRequest struct {
	Email      *openapi_types.Email `json:"email,omitempty"`
	FirstName  *string              `json:"first_name,omitempty"`
	LastName   *string              `json:"last_name,omitempty"`
	MiddleName *string              `json:"middle_name,omitempty"`
	Phone      *string              `json:"phone,omitempty"`
}

// GetRefreshRequest defines model for GetRefreshRequest.
type GetRefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// GetShortInfoAllPetResponse defines model for GetShortInfoAllPetResponse.
type GetShortInfoAllPetResponse struct {
	Items []GetShortInfoPetResponse `json:"items"`
}

// GetShortInfoPetResponse defines model for GetShortInfoPetResponse.
type GetShortInfoPetResponse struct {
	Breed string             `json:"breed"`
	Icon  PetIconEnum        `json:"icon"`
	Id    openapi_types.UUID `json:"id"`
	Name  string             `json:"name"`

	// PhotoUrl Presigned GET URL на текущую фотографию питомца, временная ссылка с TTL; null если фотографии нет
	PhotoUrl *string `json:"photo_url"`
	Species  string  `json:"species"`
}

// GetVaccinationIdResponseRequest defines model for GetVaccinationIdResponseRequest.
type GetVaccinationIdResponseRequest struct {
	Id openapi_types.UUID `json:"id"`
}

// GetVaccinationRequest defines model for GetVaccinationRequest.
type GetVaccinationRequest struct {
	// AddEventOnAdministered Если true — сервер дополнительно создаёт событие на дату введения (administered_date).
	AddEventOnAdministered *bool `json:"add_event_on_administered,omitempty"`

	// AddEventOnNext Если true и передан next_date — сервер дополнительно создаёт событие-напоминание на дату next_date.
	AddEventOnNext   *bool              `json:"add_event_on_next,omitempty"`
	AdministeredDate openapi_types.Date `json:"administered_date"`

	// EventTime Время суток для создаваемых событий (administered/next). Не хранится в самой прививке.
	EventTime *string             `json:"event_time"`
	Name      string              `json:"name"`
	NextDate  *openapi_types.Date `json:"next_date"`
}

// GetVaccinationResponse defines model for GetVaccinationResponse.
type GetVaccinationResponse struct {
	AdministeredDate openapi_types.Date `json:"administered_date"`

	// AdministeredEventId id события, связанного с этой прививкой на дату введения; null, если такое событие не создавалось.
	AdministeredEventId *openapi_types.UUID `json:"administered_event_id"`

	// FilesCount Количество прикреплённых файлов прививки (0, если файлов нет).
	FilesCount int                 `json:"files_count"`
	Id         openapi_types.UUID  `json:"id"`
	Name       string              `json:"name"`
	NextDate   *openapi_types.Date `json:"next_date"`

	// NextEventId id события-напоминания о следующей прививке; null, если такое событие не создавалось.
	NextEventId *openapi_types.UUID `json:"next_event_id"`
	PetId       openapi_types.UUID  `json:"pet_id"`
}

// GetVetVisitIdResponseRequest defines model for GetVetVisitIdResponseRequest.
type GetVetVisitIdResponseRequest struct {
	Id openapi_types.UUID `json:"id"`
}

// GetVetVisitRequest defines model for GetVetVisitRequest.
type GetVetVisitRequest struct {
	Clinic    *string            `json:"clinic"`
	Note      *string            `json:"note"`
	Reason    string             `json:"reason"`
	VisitDate openapi_types.Date `json:"visit_date"`
}

// GetVetVisitResponse defines model for GetVetVisitResponse.
type GetVetVisitResponse struct {
	Clinic *string `json:"clinic"`

	// FilesCount Количество прикреплённых файлов визита (0, если файлов нет).
	FilesCount int                `json:"files_count"`
	Id         openapi_types.UUID `json:"id"`
	Note       *string            `json:"note"`
	PetId      openapi_types.UUID `json:"pet_id"`
	Reason     string             `json:"reason"`
	VisitDate  openapi_types.Date `json:"visit_date"`
}

// ImportAllergy defines model for ImportAllergy.
type ImportAllergy struct {
	Allergen     string              `json:"allergen"`
	DetectedDate *openapi_types.Date `json:"detected_date"`

	// LocalId Клиентский UUID аллергии в локальном хранилище устройства; используется только как временный ключ ссылки внутри этого запроса и как ключ соответствия в ответе, не сохраняется на сервере.
	LocalId string  `json:"local_id"`
	Note    *string `json:"note"`

	// PetLocalId Должен совпадать с одним из pets[].local_id этого же запроса.
	PetLocalId string              `json:"pet_local_id"`
	Reaction   *string             `json:"reaction"`
	Severity   AllergySeverityEnum `json:"severity"`
}

// ImportDisease defines model for ImportDisease.
type ImportDisease struct {
	DiagnosedDate openapi_types.Date `json:"diagnosed_date"`

	// LocalId Клиентский UUID заболевания в локальном хранилище устройства; используется только как временный ключ ссылки внутри этого запроса и как ключ соответствия в ответе, не сохраняется на сервере.
	LocalId string  `json:"local_id"`
	Name    string  `json:"name"`
	Note    *string `json:"note"`

	// PetLocalId Должен совпадать с одним из pets[].local_id этого же запроса.
	PetLocalId string            `json:"pet_local_id"`
	Status     DiseaseStatusEnum `json:"status"`
}

// ImportLocalDataEvent defines model for ImportLocalDataEvent.
type ImportLocalDataEvent struct {
	Date time.Time `json:"date"`

	// LocalId Клиентский UUID события в локальном хранилище устройства; используется только как временный ключ ссылки внутри этого запроса и как ключ соответствия в ответе, не сохраняется на сервере.
	LocalId string  `json:"local_id"`
	Notes   *string `json:"notes,omitempty"`

	// PetLocalId Должен совпадать с одним из pets[].local_id этого же запроса.
	PetLocalId string       `json:"pet_local_id"`
	Type       GetEventEnum `json:"type"`

	// Value Типизированное значение события. Состав полей определяется полем type события (размеченное объединение, дискриминатор — type; см. требование «Модель значения события и реестр метрик»). На уровне схемы перечислены все возможные поля; обязательность, диапазоны и допустимость поля для конкретного type проверяются сервером по единому реестру метрик. Поле, не описанное формой value для данного type, даёт 400, а не игнорируется молча.
	//
	// Состав по типам:
	// * weight — amount (кг, 0.001–400)
	// * temperature — amount (°C, 0–50), kind (EventTemperatureKindEnum)
	// * feeding — amount (0.01–5000), unit, food
	// * water — amount (мл, 0.1–5000)
	// * activity — duration_min (1–1440), kind (EventActivityKindEnum), distance_m (0–100000, опционально)
	// * sleep — duration_min (1–1440)
	// * medication — name (1–100), dose_amount (0.001–10000) и dose_unit — только вместе, опционально
	// * hygiene — procedure
	// * mood — state
	// * urine, defecation, vomit, diarrhea — status
	// * other — label (1–50)
	Value EventValue `json:"value"`
}

// ImportLocalDataPet defines model for ImportLocalDataPet.
type ImportLocalDataPet struct {
	BirthDate *openapi_types.Date `json:"birth_date,omitempty"`

	// BodyCondition Кондиция тела питомца (body condition score), вычисляется/задаётся вручную, хранится как поле питомца.
	BodyCondition *PetBodyConditionEnum `json:"body_condition,omitempty"`
	Breed         *string               `json:"breed,omitempty"`
	Color         *string               `json:"color,omitempty"`
	Gender        *GetGenderEnum        `json:"gender,omitempty"`
	Habitation    *GetHabilitationEnum  `json:"habitation,omitempty"`

	// LocalId Клиентский UUID питомца в локальном хранилище устройства; используется только как временный ключ ссылки внутри этого запроса (для сопоставления с events[].pet_local_id), не сохраняется на сервере.
	LocalId    string  `json:"local_id"`
	Name       string  `json:"name"`
	Notes      *string `json:"notes,omitempty"`
	Species    string  `json:"species"`
	Sterilized *bool   `json:"sterilized,omitempty"`
}

// ImportLocalDataRequest defines model for ImportLocalDataRequest.
type ImportLocalDataRequest struct {
	// Allergies Опционально: переносимые аллергии. pet_local_id должен совпадать с одним из pets[].local_id этого же запроса.
	Allergies *[]ImportAllergy `json:"allergies,omitempty"`

	// Diseases Опционально: переносимые заболевания. pet_local_id должен совпадать с одним из pets[].local_id этого же запроса.
	Diseases *[]ImportDisease       `json:"diseases,omitempty"`
	Events   []ImportLocalDataEvent `json:"events"`

	// Medications Опционально: переносимые курсы лекарств. pet_local_id должен совпадать с одним из pets[].local_id этого же запроса.
	Medications *[]ImportMedication  `json:"medications,omitempty"`
	Pets        []ImportLocalDataPet `json:"pets"`
	Profile     *GetProfileRequest   `json:"profile,omitempty"`

	// Vaccinations Опционально: переносимые прививки. pet_local_id должен совпадать с одним из pets[].local_id этого же запроса.
	Vaccinations *[]ImportVaccination `json:"vaccinations,omitempty"`

	// VetVisits Опционально: переносимые визиты к ветеринару. pet_local_id должен совпадать с одним из pets[].local_id этого же запроса.
	VetVisits *[]ImportVetVisit `json:"vet_visits,omitempty"`
}

// ImportLocalDataResponse defines model for ImportLocalDataResponse.
type ImportLocalDataResponse struct {
	// Allergies Сопоставление local_id -> серверный id для каждой перенесённой аллергии, в порядке allergies запроса. Используется клиентом для фонового переноса файлов аллергии.
	Allergies         []ImportedAllergy `json:"allergies"`
	AllergiesImported int               `json:"allergies_imported"`

	// Diseases Сопоставление local_id -> серверный id для каждого перенесённого заболевания, в порядке diseases запроса. Используется клиентом для фонового переноса файлов заболевания.
	Diseases         []ImportedDisease `json:"diseases"`
	DiseasesImported int               `json:"diseases_imported"`

	// Events Сопоставление local_id -> серверный id для каждого перенесённого события, в порядке events запроса. Используется клиентом для фонового переноса файлов события (см. «Файлы события — Frontend (dataSource=local)»).
	Events         []ImportedEvent `json:"events"`
	EventsImported int             `json:"events_imported"`

	// Medications Сопоставление local_id -> серверный id для каждого перенесённого курса лекарств, в порядке medications запроса. Используется клиентом для фонового переноса файлов курса.
	Medications         []ImportedMedication `json:"medications"`
	MedicationsImported int                  `json:"medications_imported"`

	// Pets Сопоставление local_id -> серверный id для каждого перенесённого питомца, в порядке pets запроса. Используется клиентом для фонового переноса фотографий (см. «Фотография питомца — Frontend (dataSource=local)»).
	Pets            []ImportedPet `json:"pets"`
	PetsImported    int           `json:"pets_imported"`
	ProfileImported bool          `json:"profile_imported"`

	// Vaccinations Сопоставление local_id -> серверный id для каждой перенесённой прививки, в порядке vaccinations запроса. Используется клиентом для фонового переноса файлов прививки.
	Vaccinations         []ImportedVaccination `json:"vaccinations"`
	VaccinationsImported int                   `json:"vaccinations_imported"`

	// VetVisits Сопоставление local_id -> серверный id для каждого перенесённого визита к ветеринару, в порядке vet_visits запроса. Используется клиентом для фонового переноса файлов визита.
	VetVisits         []ImportedVetVisit `json:"vet_visits"`
	VetVisitsImported int                `json:"vet_visits_imported"`
}

// ImportMedication defines model for ImportMedication.
type ImportMedication struct {
	Dosage  string              `json:"dosage"`
	EndDate *openapi_types.Date `json:"end_date"`

	// EventLocalIds local_id уже переданных в этом же запросе local-событий приёма (events[].local_id), для связывания без пересчёта расписания на сервере.
	EventLocalIds *[]string `json:"event_local_ids,omitempty"`

	// FrequencyType Вид частоты приёма лекарства (по образцу раздела «Лекарства» Apple Health).
	FrequencyType MedicationFrequencyTypeEnum `json:"frequency_type"`
	IntervalDays  *int                        `json:"interval_days"`

	// LocalId Клиентский UUID курса лекарств в локальном хранилище устройства; используется только как временный ключ ссылки внутри этого запроса и как ключ соответствия в ответе, не сохраняется на сервере.
	LocalId string  `json:"local_id"`
	Name    string  `json:"name"`
	Note    *string `json:"note"`

	// PetLocalId Должен совпадать с одним из pets[].local_id этого же запроса.
	PetLocalId string                `json:"pet_local_id"`
	StartDate  *openapi_types.Date   `json:"start_date"`
	Times      *[]MedicationTimeSlot `json:"times"`
	Weekdays   *[]int                `json:"weekdays"`
}

// ImportVaccination defines model for ImportVaccination.
type ImportVaccination struct {
	AddEventOnAdministered *bool              `json:"add_event_on_administered,omitempty"`
	AddEventOnNext         *bool              `json:"add_event_on_next,omitempty"`
	AdministeredDate       openapi_types.Date `json:"administered_date"`

	// AdministeredEventLocalId local_id связанного local-события из events[] этого же запроса, если оно уже было создано на устройстве; после импорта сервер свяжет его с полем administered_event_id прививки.
	AdministeredEventLocalId *string `json:"administered_event_local_id"`
	EventTime                *string `json:"event_time"`

	// LocalId Клиентский UUID прививки в локальном хранилище устройства; используется только как временный ключ ссылки внутри этого запроса и как ключ соответствия в ответе, не сохраняется на сервере.
	LocalId  string              `json:"local_id"`
	Name     string              `json:"name"`
	NextDate *openapi_types.Date `json:"next_date"`

	// NextEventLocalId local_id связанного local-события-напоминания из events[] этого же запроса, если оно уже было создано на устройстве; после импорта сервер свяжет его с полем next_event_id прививки.
	NextEventLocalId *string `json:"next_event_local_id"`

	// PetLocalId Должен совпадать с одним из pets[].local_id этого же запроса.
	PetLocalId string `json:"pet_local_id"`
}

// ImportVetVisit defines model for ImportVetVisit.
type ImportVetVisit struct {
	Clinic *string `json:"clinic"`

	// LocalId Клиентский UUID визита к ветеринару в локальном хранилище устройства; используется только как временный ключ ссылки внутри этого запроса и как ключ соответствия в ответе, не сохраняется на сервере.
	LocalId string  `json:"local_id"`
	Note    *string `json:"note"`

	// PetLocalId Должен совпадать с одним из pets[].local_id этого же запроса.
	PetLocalId string             `json:"pet_local_id"`
	Reason     string             `json:"reason"`
	VisitDate  openapi_types.Date `json:"visit_date"`
}

// ImportedAllergy defines model for ImportedAllergy.
type ImportedAllergy struct {
	Id      openapi_types.UUID `json:"id"`
	LocalId string             `json:"local_id"`
}

// ImportedDisease defines model for ImportedDisease.
type ImportedDisease struct {
	Id      openapi_types.UUID `json:"id"`
	LocalId string             `json:"local_id"`
}

// ImportedEvent defines model for ImportedEvent.
type ImportedEvent struct {
	Id      openapi_types.UUID `json:"id"`
	LocalId string             `json:"local_id"`
}

// ImportedMedication defines model for ImportedMedication.
type ImportedMedication struct {
	Id      openapi_types.UUID `json:"id"`
	LocalId string             `json:"local_id"`
}

// ImportedPet defines model for ImportedPet.
type ImportedPet struct {
	Id      openapi_types.UUID `json:"id"`
	LocalId string             `json:"local_id"`
}

// ImportedVaccination defines model for ImportedVaccination.
type ImportedVaccination struct {
	Id      openapi_types.UUID `json:"id"`
	LocalId string             `json:"local_id"`
}

// ImportedVetVisit defines model for ImportedVetVisit.
type ImportedVetVisit struct {
	Id      openapi_types.UUID `json:"id"`
	LocalId string             `json:"local_id"`
}

// ItemsArrayActivitiesModel defines model for ItemsArrayActivitiesModel.
type ItemsArrayActivitiesModel struct {
	Date   openapi_types.Date `json:"date"`
	Events []GetEventResponse `json:"events"`
}

// MedicationFrequencyTypeEnum Вид частоты приёма лекарства (по образцу раздела «Лекарства» Apple Health).
type MedicationFrequencyTypeEnum string

// MedicationTimeSlot defines model for MedicationTimeSlot.
type MedicationTimeSlot struct {
	// DoseNote Доза для этого времени приёма; если не задана, используется общая dosage лекарства.
	DoseNote *string `json:"dose_note"`

	// Time Время приёма, HH:mm.
	Time string `json:"time"`
}

// PetBodyConditionEnum Кондиция тела питомца (body condition score), вычисляется/задаётся вручную, хранится как поле питомца.
type PetBodyConditionEnum string

// PetIconEnum defines model for PetIconEnum.
type PetIconEnum string

// PostFilesUploadUrlRequest defines model for PostFilesUploadUrlRequest.
type PostFilesUploadUrlRequest struct {
	// ContentType MIME-тип файла, должен входить в список допустимых для данного owner_type
	ContentType string `json:"content_type"`

	// Filename Опциональное исходное имя файла, как выбрано пользователем; используется читающей стороной конкретного owner_type (см. «Общие требования: Файлы сущностей»).
	Filename *string            `json:"filename,omitempty"`
	OwnerId  openapi_types.UUID `json:"owner_id"`

	// OwnerType Тип владельца файла из реестра типов владельцев, например pet_photo, event_file, vaccination_file, disease_file, vet_visit_file, allergy_file, medication_file
	OwnerType string `json:"owner_type"`
}

// PostFilesUploadUrlResponse defines model for PostFilesUploadUrlResponse.
type PostFilesUploadUrlResponse struct {
	ContentType string `json:"content_type"`

	// ExpiresIn Время жизни presigned URL в секундах
	ExpiresIn int                `json:"expires_in"`
	FileId    openapi_types.UUID `json:"file_id"`

	// UploadUrl Presigned PUT URL для прямой загрузки в S3-совместимое хранилище
	UploadUrl string `json:"upload_url"`
}

// UpdateAllergyRequest defines model for UpdateAllergyRequest.
type UpdateAllergyRequest struct {
	Allergen     *string              `json:"allergen,omitempty"`
	DetectedDate *openapi_types.Date  `json:"detected_date"`
	Note         *string              `json:"note"`
	Reaction     *string              `json:"reaction"`
	Severity     *AllergySeverityEnum `json:"severity,omitempty"`
}

// UpdateDiseaseRequest defines model for UpdateDiseaseRequest.
type UpdateDiseaseRequest struct {
	DiagnosedDate *openapi_types.Date `json:"diagnosed_date,omitempty"`
	Name          *string             `json:"name,omitempty"`
	Note          *string             `json:"note"`
	Status        *DiseaseStatusEnum  `json:"status,omitempty"`
}

// UpdateEventRequest defines model for UpdateEventRequest.
type UpdateEventRequest struct {
	Date  *time.Time         `json:"date,omitempty"`
	Notes *string            `json:"notes,omitempty"`
	PetId openapi_types.UUID `json:"pet_id"`
	Type  *GetEventEnum      `json:"type,omitempty"`

	// Value Типизированное значение события. Состав полей определяется полем type события (размеченное объединение, дискриминатор — type; см. требование «Модель значения события и реестр метрик»). На уровне схемы перечислены все возможные поля; обязательность, диапазоны и допустимость поля для конкретного type проверяются сервером по единому реестру метрик. Поле, не описанное формой value для данного type, даёт 400, а не игнорируется молча.
	//
	// Состав по типам:
	// * weight — amount (кг, 0.001–400)
	// * temperature — amount (°C, 0–50), kind (EventTemperatureKindEnum)
	// * feeding — amount (0.01–5000), unit, food
	// * water — amount (мл, 0.1–5000)
	// * activity — duration_min (1–1440), kind (EventActivityKindEnum), distance_m (0–100000, опционально)
	// * sleep — duration_min (1–1440)
	// * medication — name (1–100), dose_amount (0.001–10000) и dose_unit — только вместе, опционально
	// * hygiene — procedure
	// * mood — state
	// * urine, defecation, vomit, diarrhea — status
	// * other — label (1–50)
	Value *EventValue `json:"value,omitempty"`
}

// UpdateMedicationRequest defines model for UpdateMedicationRequest.
type UpdateMedicationRequest struct {
	Dosage  *string             `json:"dosage,omitempty"`
	EndDate *openapi_types.Date `json:"end_date"`

	// FrequencyType Вид частоты приёма лекарства (по образцу раздела «Лекарства» Apple Health).
	FrequencyType *MedicationFrequencyTypeEnum `json:"frequency_type,omitempty"`
	IntervalDays  *int                         `json:"interval_days"`
	Name          *string                      `json:"name,omitempty"`
	Note          *string                      `json:"note"`

	// RegenerateEvents Если поля расписания меняются и у курса уже есть event_ids — true пересоздаёт события по новому расписанию (жёсткое удаление старых + создание новых), false/отсутствие — сохраняет существующие события как есть.
	RegenerateEvents *bool                 `json:"regenerate_events,omitempty"`
	StartDate        *openapi_types.Date   `json:"start_date"`
	Times            *[]MedicationTimeSlot `json:"times"`
	Weekdays         *[]int                `json:"weekdays"`
}

// UpdatePetProfileRequest defines model for UpdatePetProfileRequest.
type UpdatePetProfileRequest struct {
	BirthDate *openapi_types.Date `json:"birth_date,omitempty"`

	// BodyCondition Кондиция тела питомца (body condition score), вычисляется/задаётся вручную, хранится как поле питомца.
	BodyCondition *PetBodyConditionEnum `json:"body_condition,omitempty"`
	Breed         *string               `json:"breed,omitempty"`
	Color         *string               `json:"color,omitempty"`
	Gender        *GetGenderEnum        `json:"gender,omitempty"`
	Habitation    *GetHabilitationEnum  `json:"habitation,omitempty"`
	Name          *string               `json:"name,omitempty"`
	Notes         *string               `json:"notes,omitempty"`
	Species       *string               `json:"species,omitempty"`
	Sterilized    *bool                 `json:"sterilized,omitempty"`

	// Weight Вес питомца в кг (0.001–400), опционально. Отсутствие ключа и явный null равнозначны — событие weight не создаётся. При передаче не-null числа сервер создаёт новое событие типа weight; существующие события не изменяются.
	Weight *float32 `json:"weight"`
}

// UpdateVaccinationRequest defines model for UpdateVaccinationRequest.
type UpdateVaccinationRequest struct {
	AddEventOnAdministered *bool               `json:"add_event_on_administered,omitempty"`
	AddEventOnNext         *bool               `json:"add_event_on_next,omitempty"`
	AdministeredDate       *openapi_types.Date `json:"administered_date,omitempty"`
	EventTime              *string             `json:"event_time"`
	Name                   *string             `json:"name,omitempty"`
	NextDate               *openapi_types.Date `json:"next_date"`
}

// UpdateVetVisitRequest defines model for UpdateVetVisitRequest.
type UpdateVetVisitRequest struct {
	Clinic    *string             `json:"clinic"`
	Note      *string             `json:"note"`
	Reason    *string             `json:"reason,omitempty"`
	VisitDate *openapi_types.Date `json:"visit_date,omitempty"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// IdempotencyKeyRequired defines model for IdempotencyKeyRequired.
type IdempotencyKeyRequired = openapi_types.UUID

// LanguageCode defines model for LanguageCode.
type LanguageCode string

// GetActivitiesParams defines parameters for GetActivities.
type GetActivitiesParams struct {
	PetId openapi_types.UUID `form:"pet_id" json:"pet_id"`
	From  openapi_types.Date `form:"from" json:"from"`
	To    openapi_types.Date `form:"to" json:"to"`
}

// GetActivitiesCalendarParams defines parameters for GetActivitiesCalendar.
type GetActivitiesCalendarParams struct {
	From openapi_types.Date `form:"from" json:"from"`
	To   openapi_types.Date `form:"to" json:"to"`
}

// GetActivitiesDayParams defines parameters for GetActivitiesDay.
type GetActivitiesDayParams struct {
	Date openapi_types.Date `form:"date" json:"date"`
}

// PostEventParams defines parameters for PostEvent.
type PostEventParams struct {
	// IdempotencyKey UUID v4, генерируется клиентом один раз при открытии формы добавления события; повторная отправка с тем же ключом возвращает ранее созданное событие вместо дубликата.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetEventsStatsParams defines parameters for GetEventsStats.
type GetEventsStatsParams struct {
	PetId openapi_types.UUID `form:"pet_id" json:"pet_id"`

	// Types Список значений type через запятую. По умолчанию — все типы, у которых value_kind ≠ label.
	Types  *string              `form:"types,omitempty" json:"types,omitempty"`
	From   openapi_types.Date   `form:"from" json:"from"`
	To     openapi_types.Date   `form:"to" json:"to"`
	Bucket EventStatsBucketEnum `form:"bucket" json:"bucket"`
}

// PostImportLocalDataParams defines parameters for PostImportLocalData.
type PostImportLocalDataParams struct {
	// IdempotencyKey UUID v4, генерируется клиентом один раз на попытку переноса локальных данных; повторная отправка с тем же ключом в течение окна дедупликации возвращает ранее сохранённый результат переноса вместо повторного создания сущностей.
	IdempotencyKey IdempotencyKeyRequired `json:"Idempotency-Key"`
}

// PostPetParams defines parameters for PostPet.
type PostPetParams struct {
	// IdempotencyKey UUID v4, генерируется клиентом один раз при открытии формы добавления события; повторная отправка с тем же ключом возвращает ранее созданное событие вместо дубликата.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetPetAllergiesParams defines parameters for GetPetAllergies.
type GetPetAllergiesParams struct {
	// Limit Максимум записей в ответе. По умолчанию 50, значения больше 200 молча ограничиваются до 200.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для пагинации. По умолчанию 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostAllergyParams defines parameters for PostAllergy.
type PostAllergyParams struct {
	// IdempotencyKey UUID v4, генерируется клиентом один раз при открытии формы добавления события; повторная отправка с тем же ключом возвращает ранее созданное событие вместо дубликата.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetPetDiseasesParams defines parameters for GetPetDiseases.
type GetPetDiseasesParams struct {
	// Limit Максимум записей в ответе. По умолчанию 50, значения больше 200 молча ограничиваются до 200.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для пагинации. По умолчанию 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostDiseaseParams defines parameters for PostDisease.
type PostDiseaseParams struct {
	// IdempotencyKey UUID v4, генерируется клиентом один раз при открытии формы добавления события; повторная отправка с тем же ключом возвращает ранее созданное событие вместо дубликата.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetPetEventsParams defines parameters for GetPetEvents.
type GetPetEventsParams struct {
	// Limit Максимум записей в ответе. По умолчанию 50, значения больше 200 молча ограничиваются до 200.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для пагинации. По умолчанию 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Полнотекстовый фильтр без учёта регистра по notes и по свободнотекстовому подполю значения события (other.label, medication.name). Пустая строка или отсутствие параметра — фильтр не применяется.
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// GetPetMedicationsParams defines parameters for GetPetMedications.
type GetPetMedicationsParams struct {
	// Limit Максимум записей в ответе. По умолчанию 50, значения больше 200 молча ограничиваются до 200.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для пагинации. По умолчанию 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostMedicationParams defines parameters for PostMedication.
type PostMedicationParams struct {
	// IdempotencyKey UUID v4, генерируется клиентом один раз при открытии формы добавления события; повторная отправка с тем же ключом возвращает ранее созданное событие вместо дубликата.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetPetVaccinationsParams defines parameters for GetPetVaccinations.
type GetPetVaccinationsParams struct {
	// Limit Максимум записей в ответе. По умолчанию 50, значения больше 200 молча ограничиваются до 200.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для пагинации. По умолчанию 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostVaccinationParams defines parameters for PostVaccination.
type PostVaccinationParams struct {
	// IdempotencyKey UUID v4, генерируется клиентом один раз при открытии формы добавления события; повторная отправка с тем же ключом возвращает ранее созданное событие вместо дубликата.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetPetVetVisitsParams defines parameters for GetPetVetVisits.
type GetPetVetVisitsParams struct {
	// Limit Максимум записей в ответе. По умолчанию 50, значения больше 200 молча ограничиваются до 200.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для пагинации. По умолчанию 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostVetVisitParams defines parameters for PostVetVisit.
type PostVetVisitParams struct {
	// IdempotencyKey UUID v4, генерируется клиентом один раз при открытии формы добавления события; повторная отправка с тем же ключом возвращает ранее созданное событие вместо дубликата.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// PatchAllergyJSONRequestBody defines body for PatchAllergy for application/json ContentType.
type PatchAllergyJSONRequestBody = UpdateAllergyRequest

// PostGuestJSONRequestBody defines body for PostGuest for application/json ContentType.
type PostGuestJSONRequestBody = GetGuestRequest

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = GetLoginRequest

// PostLogoutJSONRequestBody defines body for PostLogout for application/json ContentType.
type PostLogoutJSONRequestBody = GetRefreshRequest

// PostRefreshJSONRequestBody defines body for PostRefresh for application/json ContentType.
type PostRefreshJSONRequestBody = GetRefreshRequest

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody = GetLoginRequest

// PatchDiseaseJSONRequestBody defines body for PatchDisease for application/json ContentType.
type PatchDiseaseJSONRequestBody = UpdateDiseaseRequest

// PostEventJSONRequestBody defines body for PostEvent for application/json ContentType.
type PostEventJSONRequestBody = GetEventRequest

// PatchEventJSONRequestBody defines body for PatchEvent for application/json ContentType.
type PatchEventJSONRequestBody = UpdateEventRequest

// PostFilesUploadUrlJSONRequestBody defines body for PostFilesUploadUrl for application/json ContentType.
type PostFilesUploadUrlJSONRequestBody = PostFilesUploadUrlRequest

// PostImportLocalDataJSONRequestBody defines body for PostImportLocalData for application/json ContentType.
type PostImportLocalDataJSONRequestBody = ImportLocalDataRequest

// PatchMedicationJSONRequestBody defines body for PatchMedication for application/json ContentType.
type PatchMedicationJSONRequestBody = UpdateMedicationRequest

// PostPetJSONRequestBody defines body for PostPet for application/json ContentType.
type PostPetJSONRequestBody = GetPetProfileRequest

// PutPetJSONRequestBody defines body for PutPet for application/json ContentType.
type PutPetJSONRequestBody = UpdatePetProfileRequest

// PostAllergyJSONRequestBody defines body for PostAllergy for application/json ContentType.
type PostAllergyJSONRequestBody = GetAllergyRequest

// PostDiseaseJSONRequestBody defines body for PostDisease for application/json ContentType.
type PostDiseaseJSONRequestBody = GetDiseaseRequest

// PostMedicationJSONRequestBody defines body for PostMedication for application/json ContentType.
type PostMedicationJSONRequestBody = GetMedicationRequest

// PostVaccinationJSONRequestBody defines body for PostVaccination for application/json ContentType.
type PostVaccinationJSONRequestBody = GetVaccinationRequest

// PostVetVisitJSONRequestBody defines body for PostVetVisit for application/json ContentType.
type PostVetVisitJSONRequestBody = GetVetVisitRequest

// PostProfileJSONRequestBody defines body for PostProfile for application/json ContentType.
type PostProfileJSONRequestBody = GetProfileRequest

// PutProfileJSONRequestBody defines body for PutProfile for application/json ContentType.
type PutProfileJSONRequestBody = GetProfileUpdateRequest

// PatchVaccinationJSONRequestBody defines body for PatchVaccination for application/json ContentType.
type PatchVaccinationJSONRequestBody = UpdateVaccinationRequest

// PatchVetVisitJSONRequestBody defines body for PatchVetVisit for application/json ContentType.
type PatchVetVisitJSONRequestBody = UpdateVetVisitRequest
