// Package adminapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package adminapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AdminKeyScopes = "AdminKey.Scopes"
)

// Defines values for AdminBannerCtaAction.
const (
	Deeplink AdminBannerCtaAction = "deeplink"
	Store    AdminBannerCtaAction = "store"
	Url      AdminBannerCtaAction = "url"
)

// Defines values for AdminBannerFrequency.
const (
	EveryLaunch AdminBannerFrequency = "every_launch"
	Once        AdminBannerFrequency = "once"
)

// Defines values for AdminBannerLayout.
const (
	Carousel AdminBannerLayout = "carousel"
	Cover    AdminBannerLayout = "cover"
	Dialog   AdminBannerLayout = "dialog"
	Poster   AdminBannerLayout = "poster"
	Sheet    AdminBannerLayout = "sheet"
)

// Defines values for AdminBannerTone.
const (
	Attention AdminBannerTone = "attention"
	Info      AdminBannerTone = "info"
	Negative  AdminBannerTone = "negative"
	Positive  AdminBannerTone = "positive"
	Promo     AdminBannerTone = "promo"
)

// Defines values for AdminErrorCode.
const (
	BADREQUEST      AdminErrorCode = "BAD_REQUEST"
	CONFLICT        AdminErrorCode = "CONFLICT"
	FORBIDDEN       AdminErrorCode = "FORBIDDEN"
	INTERNALERROR   AdminErrorCode = "INTERNAL_ERROR"
	NOTFOUND        AdminErrorCode = "NOT_FOUND"
	RATELIMITED     AdminErrorCode = "RATE_LIMITED"
	UNAUTHORIZED    AdminErrorCode = "UNAUTHORIZED"
	VALIDATIONERROR AdminErrorCode = "VALIDATION_ERROR"
)

// Defines values for AdminLocale.
const (
	En AdminLocale = "en"
	Ru AdminLocale = "ru"
)

// AdminBannerCtaAction defines model for AdminBannerCtaAction.
type AdminBannerCtaAction string

// AdminBannerFrequency defines model for AdminBannerFrequency.
type AdminBannerFrequency string

// AdminBannerLayout defines model for AdminBannerLayout.
type AdminBannerLayout string

// AdminBannerListResponse defines model for AdminBannerListResponse.
type AdminBannerListResponse struct {
	Items []BannerDocResponse `json:"items"`
}

// AdminBannerTone defines model for AdminBannerTone.
type AdminBannerTone string

// AdminErrorCode Копия ErrorCodeEnum клиентской спеки; формат ошибки тот же ({ code, message, payload }).
type AdminErrorCode string

// AdminErrorResponse defines model for AdminErrorResponse.
type AdminErrorResponse struct {
	// Code Копия ErrorCodeEnum клиентской спеки; формат ошибки тот же ({ code, message, payload }).
	Code    AdminErrorCode `json:"code"`
	Message string         `json:"message"`

	// Payload Для VALIDATION_ERROR — массив AdminValidationIssue.
	Payload *interface{} `json:"payload,omitempty"`
}

// AdminLocale Поддерживаемые языки (значения LanguageCode); ru — язык по умолчанию.
type AdminLocale string

// AdminValidationIssue defines model for AdminValidationIssue.
type AdminValidationIssue struct {
	// Path Путь к полю документа, например translations.ru.title или slides[2].translations.ru.title.
	Path   string `json:"path"`
	Reason string `json:"reason"`
}

// BannerDoc Единый нелокализованный документ баннера (все переводы). Отсутствующие поля трактуются как null; isShow по умолчанию true, priority — 0, массивы — пустые.
type BannerDoc struct {
	Cta       *BannerDocCta         `json:"cta"`
	EndsAt    *time.Time            `json:"endsAt"`
	Frequency AdminBannerFrequency  `json:"frequency"`
	IsShow    *bool                 `json:"isShow,omitempty"`
	Layout    AdminBannerLayout     `json:"layout"`
	Priority  *int                  `json:"priority,omitempty"`
	Slides    *[]BannerDocSlide     `json:"slides,omitempty"`
	StartsAt  *time.Time            `json:"startsAt"`
	Targeting *[]BannerDocTargeting `json:"targeting,omitempty"`
	Tone      *AdminBannerTone      `json:"tone"`

	// Translations Карта «код языка → поля»; обязан содержать ru.
	Translations map[string]BannerDocTranslation `json:"translations"`

	// UserIds Если не пусто — баннер отдаётся только этим пользователям.
	UserIds *[]openapi_types.UUID `json:"userIds,omitempty"`
}

// BannerDocCta defines model for BannerDocCta.
type BannerDocCta struct {
	Action *AdminBannerCtaAction `json:"action"`
	Target *string               `json:"target"`
}

// BannerDocImage defines model for BannerDocImage.
type BannerDocImage struct {
	Blurhash *string `json:"blurhash"`

	// Url Абсолютный https URL.
	Url string `json:"url"`
}

// BannerDocResponse defines model for BannerDocResponse.
type BannerDocResponse struct {
	CreatedAt time.Time             `json:"createdAt"`
	Cta       *BannerDocCta         `json:"cta"`
	EndsAt    *time.Time            `json:"endsAt"`
	Frequency AdminBannerFrequency  `json:"frequency"`
	Id        openapi_types.UUID    `json:"id"`
	IsShow    *bool                 `json:"isShow,omitempty"`
	Layout    AdminBannerLayout     `json:"layout"`
	Priority  *int                  `json:"priority,omitempty"`
	Slides    *[]BannerDocSlide     `json:"slides,omitempty"`
	StartsAt  *time.Time            `json:"startsAt"`
	Targeting *[]BannerDocTargeting `json:"targeting,omitempty"`
	Tone      *AdminBannerTone      `json:"tone"`

	// Translations Карта «код языка → поля»; обязан содержать ru.
	Translations map[string]BannerDocTranslation `json:"translations"`

	// UserIds Если не пусто — баннер отдаётся только этим пользователям.
	UserIds *[]openapi_types.UUID `json:"userIds,omitempty"`
}

// BannerDocSlide Порядок слайдов задаётся порядком элементов массива (position с 1).
type BannerDocSlide struct {
	// Translations Карта «код языка → поля».
	Translations map[string]BannerDocSlideTranslation `json:"translations"`
}

// BannerDocSlideTranslation defines model for BannerDocSlideTranslation.
type BannerDocSlideTranslation struct {
	Body  *string         `json:"body"`
	Image *BannerDocImage `json:"image"`
	Title *string         `json:"title"`
}

// BannerDocTargeting defines model for BannerDocTargeting.
type BannerDocTargeting struct {
	// Params Параметры правила: platform {values}, app_version {min,max}, language {values}, has_pets {value}.
	Params map[string]interface{} `json:"params"`

	// Type platform | app_version | language | has_pets; не более одного правила каждого типа.
	Type string `json:"type"`
}

// BannerDocTranslation defines model for BannerDocTranslation.
type BannerDocTranslation struct {
	Badge          *string         `json:"badge"`
	Body           *string         `json:"body"`
	CtaLabel       *string         `json:"ctaLabel"`
	Image          *BannerDocImage `json:"image"`
	Overline       *string         `json:"overline"`
	SecondaryLabel *string         `json:"secondaryLabel"`
	Title          *string         `json:"title"`
}

// PatchBannerRequest defines model for PatchBannerRequest.
type PatchBannerRequest struct {
	IsShow bool `json:"isShow"`
}

// BannerId defines model for BannerId.
type BannerId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = AdminErrorResponse

// InternalError defines model for InternalError.
type InternalError = AdminErrorResponse

// NotFound defines model for NotFound.
type NotFound = AdminErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = AdminErrorResponse

// AdminCreateBannerJSONRequestBody defines body for AdminCreateBanner for application/json ContentType.
type AdminCreateBannerJSONRequestBody = BannerDoc

// AdminPatchBannerJSONRequestBody defines body for AdminPatchBanner for application/json ContentType.
type AdminPatchBannerJSONRequestBody = PatchBannerRequest

// AdminPutBannerJSONRequestBody defines body for AdminPutBanner for application/json ContentType.
type AdminPutBannerJSONRequestBody = BannerDoc
